### ISSUE TITLE
Alternatives to GammaCorrectionEffect

### ISSUE THREAD

**Issue by donmccurdy** [pmndrs/postprocessing#370]
I noticed `GammaCorrectionEffect` is deprecated, with the message "Set WebGLRenderer.outputEncoding to sRGBEncoding instead.". The term "gamma" is best avoided in the context of output color space transforms, and three.js is shifting away from that, so +1 for deprecating the effect as it exists today. I also like how this library respects `renderer.outputEncoding`, so a strong +1 for that feature too.

However ... I think it's still a good idea to have _some_ way of doing color space conversions in an Effect. Users may not want color correction to be the absolute last stop of their post-processing pipeline, and there quite a few use cases for that. A simple example I'll suggest here is the existing BrightnessContrastEffect — if you're doing a lerp/multiplier for contrast (there are more complex methods too, with LUTs or contrast curves..), you [probably want to do that in sRGB space](https://forum.unity.com/threads/shader-function-to-adjust-texture-contrast.457635/) and not Linear-sRGB. So a reasonable stack could look something like:

```js
const pass = new EffectPass(camera, [
  ...
  new ColorSpaceTransformEffect(THREE.LinearSRGBColorSpace, THREE.SRGBColorSpace),
  new BrightnessContrastEffect(BlendFunction.NORMAL, 0.0, 0.5),
]);
```

In this example you don't want an additional color space conversion after the contrast effect. I'm not completely sure how to prevent that, just setting `renderer.outputEncoding = LinearEncoding` seems semantically confusing and could have side effects. Possibly EffectPass could do something clever if it sees ColorSpaceTransformEffect in the effects stack with a matching destination color space to `renderer.outputEncoding`. 🤔

**Comment by vanruesc** [comment]
> if you're doing a lerp/multiplier for contrast (there are more complex methods too, with LUTs or contrast curves..), you [probably want to do that in sRGB space](https://forum.unity.com/threads/shader-function-to-adjust-texture-contrast.457635/) and not Linear-sRGB

Interesting, didn't know that. I think `LUTEffect` also has an `inputEncoding` setting which is `sRGBEncoding` by default since most LUTs expect sRGB input colors.

> In this example you don't want an additional color space conversion after the contrast effect. I'm not completely sure how to prevent that.

It's possible to disable output encoding via `EffectPass.fullscreenMaterial.encodeOutput = false`.

> Possibly EffectPass could do something clever if it sees ColorSpaceTransformEffect

That's one option, but we should be careful with automagical features. I'd be in favor of letting the user configure things explicitly. And I'm ok with adding a `ColorSpaceTransformEffect` :+1: We could explain how to use it in the doc comments and later the new manual.

**Comment by donmccurdy** [comment]
> I think LUTEffect also has an inputEncoding setting which is sRGBEncoding by default since most LUTs expect sRGB input colors....

Ohhhh that's a huge help to know! Thank you, I'd been scratching my head over why some output didn't look right. I'm in the rare scenario where the input is not sRGB.😱 🙏

> ...That's one option, but we should be careful with automagical features. 

Agreed on "automagical" being scary, especially with color spaces. I do prefer explicit configuration here as well. I think the risk I see with `renderer.outputEncoding = LinearEncoding`  (in this situation) is that we actually mean "please don't apply a color space transform when writing to the canvas" ... but the final output is really sRGB, not Linear-sRGB.  That feels weird but I can't think of an actual problem at the moment, so maybe it's fine with the `.encodeOutput` option. The option could be promoted to the Pass if needed maybe, but no strong opinion at the moment.

**Comment by vanruesc** [comment]
> And I'm ok with adding a `ColorSpaceTransformEffect`

I wonder if it would be better to add this functionality to `Effect` instead :thinking:

@donmccurdy What do you think about an API that would let users specify `Effect.inputColorSpace` and `Effect.outputColorSpace`? The default of both fields would be something like `ColorSpace.LINEAR_SRGB` (no-op). If an effect specifies `ColorSpace.SRGB` for the input, the `EffectPass` would inject shader code to apply the conversion right before the effect's `mainImage` gets called. Depending on `outputColorSpace`, the output of the effect could then either remain in that color space (no-op) or it could be converted back to `ColorSpace.LINEAR_SRGB` (default).

**Comment by donmccurdy** [comment]
I like the idea of letting Effect's specify, yeah. Even just an `effect.processColorSpace` property, specifying what the Effect needs to work with, and output is determined by whatever is next in the chain. Similar to OpenColorIO's [Look.processSpace](https://opencolorio.readthedocs.io/en/latest/guides/authoring/looks.html?highlight=process%20space#id2).

I'd try to avoid the "Linear-sRGB = no-op" assumption though. Could have some effects that really need to be done in Linear-sRGB, some that really need to be done in sRGB, or some that don't care. three.js currently has three constants available:

- NoColorSpace
- SRGBColorSpace
- LinearSRGBColorSpace

THREE.NoColorSpace can probably be treated as a no-op. This list might grow as WebGL or WebGPU APIs allow more.

**Comment by vanruesc** [comment]
Got it, thanks for the feedback :+1:

**Comment by vanruesc** [comment]
Added experimental `inputColorSpace` and `outputColorSpace` settings to `Effect` in `postprocessing@6.28.0`. The `BrightnessContrastEffect` now sets the `inputColorSpace` to `sRGBEncoding`.

The effect shader will convert results back to linear-sRGB if the working color space is sRGB after the last effect. This step is only necessary because there is currently no way to know if the output will actually be converted to sRGB via `<encode_output>`.

**Comment by vanruesc** [comment]
I've carried over the settings for `Effect.inputColorSpace` and `Effect.outputColorSpace` to v7. These settings allow color space transformations to be tracked within effect chains. Here's the documentation for reference:

#### inputColorSpace
> Default is `NoColorSpace`, meaning no change.
> Ensures that the input colors are in the specified color space, converting them if necessary.

#### outputColorSpace
> Default is `NoColorSpace`, meaning no change.
> Should only be defined if this effect converts the input colors to a different color space.
