### ISSUE TITLE
Artifacts in various LUT .cube

### ISSUE THREAD

**Issue by Ben-Mack** [pmndrs/postprocessing#375]
Various of LUT .cube files I tried results in weird color, although these files still working fine in Max

Correct result in Max:
![image](https://user-images.githubusercontent.com/6309393/174242099-a38ca39f-2dbd-47db-9759-ad5bbcfbb054.png)
Result in postprocessing:
![image](https://user-images.githubusercontent.com/6309393/174242132-9864d902-c3da-4996-839c-ee267bb5925f.png)

Reproducable sandbox: https://codesandbox.io/s/great-christian-h2flzj

Please rename these attached txt as .cube to try:
[1.cube.txt](https://github.com/pmndrs/postprocessing/files/8924911/1.cube.txt)
[2.cube.txt](https://github.com/pmndrs/postprocessing/files/8924913/2.cube.txt)
[3.cube.txt](https://github.com/pmndrs/postprocessing/files/8924914/3.cube.txt)

**Comment by vanruesc** [comment]
This seems to be a bug in `LUTCubeLoader`. I've attached an image of the loaded LUT which shows that the color channels are misaligned for some reason. Working on a fix.
<details>
<summary>Broken LUT</summary>
<img src="https://user-images.githubusercontent.com/9214917/174447870-19debd56-12f6-48de-814a-a6c286d47bf4.png">
</details>

**Comment by Ben-Mack** [comment]
Wow, this is great, thanks a lot !!
