### ISSUE TITLE
Blur outline on interior

### ISSUE THREAD

**Issue by canadaduane** [pmndrs/postprocessing#379]
### Is your feature request related to a problem?

The OutlineEffect with `blur: true` smooths the outline on the exterior of the shape, but leaves the interior with aliasing. Would it be possible to blur the interior as well?

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/129/177094757-9744692b-52dd-4a42-86ef-0b0f594749ae.png)

In the image above, I would like a "smooth outline" all around the rock, with no aliasing.

### Describe alternatives you've considered

Adding an anti-alias (e.g. SMAA) effect is something I'm trying not to do for the sake of speed.

**Comment by vanruesc** [comment]
Added an experimental `multisampling` setting to `OutlineEffect` in `postprocessing@6.28.2`.

This can be used as a ctor parameter or via a property:

```js
const effect = new OutlineEffect(scene, camera, {
	multisampling: Math.min(4, renderer.capabilities.maxSamples),
	...
});

effect.multisampling = Math.min(4, renderer.capabilities.maxSamples);
```

Requires three &ge; r138.
