### ISSUE TITLE
FXAAEffect is not exported in types

### ISSUE THREAD

**Issue by canadaduane** [pmndrs/postprocessing#380]
### Description of the bug

Although defined and re-exported [here](https://github.com/pmndrs/postprocessing/blob/main/src/effects/index.js#L13), the `FXAAEffect` class is not exported in the typescript types.

See https://github.com/pmndrs/postprocessing/blob/main/types/postprocessing.d.ts

### Library versions used

 - Three: 0.141.0
 - Post Processing: 6.28.1

**Comment by vanruesc** [comment]
Updated types in `postprocessing@6.28.2`. Let me know if something's still broken.
