### ISSUE TITLE
Outline doesn't clear after use

### ISSUE THREAD

**Issue by canadaduane** [pmndrs/postprocessing#383]
### Description of the bug

The OutlineEffect is shown over top of the scene even after the selection (set of selected objects) has been set to empty.

### To Reproduce

Create an outline on an object, then remove it.

### Expected behavior

The outline should be cleared after it is no longer used.

### Screenshots

Before (6.28.1):
![image](https://user-images.githubusercontent.com/129/178544042-cf675ae5-f40f-4ab6-a933-d158a12ef517.png)
![image](https://user-images.githubusercontent.com/129/178544098-5f7a45e7-adb6-425b-914d-77dec34e9900.png)

After (6.28.2):
![image](https://user-images.githubusercontent.com/129/178544378-96e9eecd-e5b0-4e1d-84b2-882595d4858c.png)

### Library versions used

 - Three: 0.141.0
 - Post Processing: 6.28.2

### Desktop

 - OS: Linux/Pop!_OS
 - Browser: Firefox 102.0
 - Graphics hardware: Intel

**Comment by vanruesc** [comment]
Thanks for the report, I'm able to reproduce the issue. This is a weird bug though :thinking: multisampling seems to mess with the buffer clearing somehow. I'll release a fix tomorrow.

**Comment by canadaduane** [comment]
The latest update looks good! Thank you.
