### ISSUE TITLE
Is viewport respected?

### ISSUE THREAD

**Issue by drone1** [pmndrs/postprocessing#386]
Simple question. I don't see anything about the viewport or examples of it used. My application renders multiple scenes within the same buffer using scissor/viewport. Would love to use this but wanted to ask before I spend any time. Thanks for your time.

**Comment by vanruesc** [comment]
This is currently not supported, but it can be done with hacks: https://codesandbox.io/s/long-darkness-szcisb?file=/src/App.js
I'll look into options to add automatic support for `WebGLRenderer.setViewport` and `WebGLRenderer.setScissor`.

**Comment by drone1** [comment]
That would be wonderful. Thank you!

**Comment by xuchaozou** [comment]
Please take a look again. It is multiple cameras rendering the same scene. The specific description and code are in #507  , thank you

**Comment by drone1** [comment]
I'd like to be able to render multiple scenes with multiple cameras, not a
single scene. Is it supported? Thank you so much!

**Comment by vanruesc** [comment]
@drone1 You can use multiple `RenderPass` instances to render multiple scenes. Make sure to set `RenderPass.clearPass.enabled = false` if you want to render the scenes to the same frame buffer. Depending on your use case, your composition may require saving intermediate render results in textures via `CopyPass`. Blending textures together can be done with `TextureEffect`.

**Comment by jo-chemla** [comment]
I've got the feeling that the `scissors/viewport` example in the codesandbox could be useful to have a screen which would be split (eg first left third side of the screen with a given `EffectPass` applied, center third with another, and right third with again another). This should be less performance hungry than doing full-screen RenderPass with different `EffectPasses` and combining them - for example via a `ShaderPass`, right?

**Comment by vanruesc** [comment]
@jo-chemla Proper support for scissor/viewport settings is planned for v7.

Closing this in favor of #570.

**Comment by jo-chemla** [comment]
Thanks for getting back, I'll follow the scissor/viewport v7 implementation thread - just thought it could be hacked in the meantime with the current v6 codesandbox, but waiting for proper support in v7 is a great alternative. 

And thanks for the awesome work on the `postprocessing` lib!
