### ISSUE TITLE
"linearToRelativeLuminance()" has been renamed 

### ISSUE THREAD

**Issue by michealparks** [pmndrs/postprocessing#394]
### Description of the bug

When force-installing Three.js r143 alongside the latest version of postprocessing I encounter the following error:
<img width="831" alt="Screen Shot 2022-08-01 at 20 29 53" src="https://user-images.githubusercontent.com/3834780/182266871-6fb5cc25-a391-4e3f-ac9a-eaba542d7e09.png">

It appears that the latest version of Three.js has renamed this function to `luminance()`.

A quick search of postprocessing shows that this function is used in a few shaders, such as "src/effects/glsl/fxaa.frag".

Not a big deal since I'm technically not using a supported version, but figured I'd flag this if it wasn't on the radar! Thank you for the awesome library!

Relevant PR: https://github.com/mrdoob/three.js/pull/24347

**Comment by vanruesc** [comment]
Thanks for the report! This will be fixed in the next release via e69d6ed.

**Comment by vanruesc** [comment]
Fixed in `postprocessing@6.28.5`.
