### ISSUE TITLE
EffectPass introduces facing problems with InstancedGeometry

### ISSUE THREAD

**Issue by emmelleppi** [pmndrs/postprocessing#402]
Hello!

I premise that I have not yet been able to reproduce the bug on a codesandbox because the model I am using is in a special format and I have to ask the client I am working for to export a gltf one. 
As soon as I can I'll do that, in the meantime I'll expose the problem I'm experiencing, maybe we don't even need the demo.

I am using a simple pipeline with `RenderPass + EffectPass[BloomEffect]`, to render a lowpoly model as shown in the attached image.
Basically it is a model of a rock made up of several pieces, to which I will then have to apply an animation for the explosion (I think this info is not very relevant)

This model must be reproduced several times, so I am using an `InstancedBufferGeometry`.

The bug consists of a strange rendering of the mesh faces, in particular these strange artefacts increase as the distance from the camera increases. as shown in the figure.
In particular the problem only occurs when I use the `EffectPass`, even when it has no effect and is therefore "empty".
If I only use RenderPass instead, there is no problem whatsoever

I am already aware of the possible problems with `InstancedBufferGeometry` and the use of the `OverrideMaterialManager`, but using only the `BloomEffect` should not be the case, right? (in any case the bug exists even with `workaroundEnabled`)

I don't seem to be doing strange things at the code level

```js
OverrideMaterialManager.workaroundEnabled = true;
...
const renderer = new THREE.WebGLRenderer({ canvas: this.canvas, context: this.gl, powerPreference: 'high-performance', antialias: false, stencil: false, depth: false });
...
this.composer = new EffectComposer(this.renderer, {
	frameBufferType: THREE.HalfFloatType,
	multisampling: 8,
});

this.renderPass = new RenderPass(this.scene, this.camera);
this.composer.addPass(this.renderPass);

this.bloomEfx = new BloomEffect({
	mipmapBlur: true,
});
this.effectPass = new EffectPass(this.camera, this.bloomEfx);
this.composer.addPass(this.effectPass);
```

The doubt came to me that this is a model-related problem. But then I cannot explain the different behaviour with and without EffectPass.

### Library versions used
 - Three: ^0.143.0
 - Post Processing: ^6.28.5
 
 Thank you!

**Comment by vanruesc** [comment]
Thanks for the report!

Does this also happen when you disable multisampling?

**Comment by emmelleppi** [comment]
Hey super quick!

Yes, just tried with this code and I'm having the same behaviour

```js
		this.composer = new EffectComposer(this.renderer, {
			frameBufferType: THREE.HalfFloatType,
			multisampling: 0,
		});
```

**Comment by emmelleppi** [comment]
oh! I am looking at the code for `OverrideMaterialManager.js`

is it possible that the problem stems from the fact that I am not using [InstancedMesh](https://threejs.org/docs/index.html?q=inst#api/en/objects/InstancedMesh) but [InstancedBufferGeometry](https://threejs.org/docs/index.html?q=inst#api/en/core/InstancedBufferGeometry)?

In particular I'm referring to [this line of code](https://github.com/pmndrs/postprocessing/blob/e238f09cf253dbc680df19d9c6abe66b1bc74ea7/src/core/OverrideMaterialManager.js#L172)

**Comment by vanruesc** [comment]
I don't think this is related to the `OverrideMaterialManager`, and the model is probably fine too. The steplike artifacts make me think it's somehow related to depth precision :thinking: 

If you only use a `RenderPass`, the scene is rendered directly to screen and when you add a fullscreen pass, the scene is rendered to an internal buffer instead. But rendering to the canvas should cause other depth issues if you create the renderer correctly, because the canvas wouldn't have a depth buffer.

This means that the following code is wrong, because the gl parameters are ignored when you provide a canvas or a context:
```js
const renderer = new THREE.WebGLRenderer({ canvas: this.canvas, context: this.gl, powerPreference: 'high-performance', antialias: false, stencil: false, depth: false });
```

It should be this instead:

```js
// https://www.khronos.org/webgl/public-mailing-list/public_webgl/1703/msg00022.php
canvas.addEventListener("webglcontextrestored", () => {});
canvas.addEventListener("webglcontextlost", (event) => {

	event.preventDefault();
	window.location.reload();

}, false);

const renderer = new THREE.WebGLRenderer({
	powerPreference: "high-performance",
	antialias: false,
	stencil: false,
	depth: false,
	canvas
});
```

Maybe the device you're testing on doesn't support `UnsignedIntType` depth. Please try enabling `stencilBuffer` to check if that fixes the issue:

```js
const composer = new EffectComposer(renderer, { stencilBuffer: true });
```

**Comment by emmelleppi** [comment]
> Maybe the device you're testing on doesn't support `UnsignedIntType` depth. Please try enabling `stencilBuffer` to check if that fixes the issue:
> 
> ```js
> const composer = new EffectComposer(renderer, { stencilBuffer: true });
> ```

It works!
just to understand, is this a workaround that affects my performance in some way or can we call it a solution to the problem?

**Comment by vanruesc** [comment]
That's a solution, but it means that your device is not WebGL compliant and claims that it supports `UnsignedIntType`, but uses a low precision fallback instead :cry:

**Comment by vanruesc** [comment]
With `stencilBuffer` set to `true`, the `EffectComposer` uses `UnsignedInt248Type` instead for the depth texture which absolutely has to be supported by all devices. I'm considering using that as the new default now that there's actually a reported case of `UnsignedIntType` failing.

**Comment by vanruesc** [comment]
> your device is not WebGL compliant

Actually it is compliant, the spec just says that devices may chose to use lower precision like 16 bits which kind of makes sense since `UnsignedIntType` doesn't specify the size.

**Comment by emmelleppi** [comment]
thanks for the explanation, everything is clearer now
thank you so much!

**Comment by vanruesc** [comment]
I had to change the default depth texture type back to `UnsignedIntType` in `postprocessing@6.28.7` because the previous switch to `UnsignedInt248Type` caused another issue with multisampling due to a missing stencil buffer.

I recommend enabling `stencilBuffer` explicitly if you require at least 24 bits of depth precision on any device. Otherwise try to tune your camera near/far plane settings to still produce satisfactory results with lower precision if possible.
