### ISSUE TITLE
Setting MipMapBlurPass.levels makes the value keep increasing

### ISSUE THREAD

**Issue by optimus007** [pmndrs/postprocessing#408]
### Description of the bug

As discussed on discord this might be an issue with the setter

### To Reproduce

Each time the `bloomEffect.mipmapBlurPass.levels` is set between 1 and 9 with step size of 1 , the value keeps increasing/stacking and eventually get `"Feedback loop formed between Framebuffer and active Texture."
`

### Library versions used

 - Three: [r144]
 - Post Processing: [6.28.7]

**Comment by vanruesc** [comment]
Thanks for the report! This will be fixed in the next release via 3a45746.

**Comment by vanruesc** [comment]
Fixed in `postprocessing@6.29.0`.
