### ISSUE TITLE
Allow disabled updateStyle when setting renderer

### ISSUE THREAD

**Issue by alexpineda** [pmndrs/postprocessing#411]
### Is your feature request related to a problem?

https://github.com/pmndrs/postprocessing/blob/main/src/core/EffectComposer.js#L231

I'm experimenting with OffScreenCanvas and it seems as though setting the style attribute is forbidden. Presently this is unavoidable due to the fact that setRenderer() calls `renderer.setSize()` with the third parameter undefined which will be interpreted as update style in the three renderer.

### Describe the solution you'd like

Simply add an option that is passed through.

**Comment by vanruesc** [comment]
Thanks for the report!

I think the call to `renderer.setSize(width, height, updateStyle);` in `setSize` can be avoided with a bit of refactoring.

**Comment by vanruesc** [comment]
Fixed in `postprocessing@6.29.0`.
