### ISSUE TITLE
Minor: blurPass and getBlurPass both marked as deprecated in DepthOfFieldEffect

### ISSUE THREAD

**Issue by alexpineda** [pmndrs/postprocessing#415]
property value here marked as deprecated:

https://github.com/pmndrs/postprocessing/blob/main/src/effects/DepthOfFieldEffect.js#L172

`getBlurPass()` here marked as deprecated:
https://github.com/pmndrs/postprocessing/blob/main/src/effects/DepthOfFieldEffect.js#L313

No where else to go!

**Comment by vanruesc** [comment]
Fixed in `postprocessing@6.29.1`.
