### ISSUE TITLE
Transparency blending handled differently compared to not using EffectComposer

### ISSUE THREAD

**Issue by nz303** [pmndrs/postprocessing#421]
### Description of the bug

When using EffectComposer, transparent blending looks differently compared to using no post effects.
Thus, if you are using the same scene and render it without post effects on mobile and with post effects on tier3-desktops the scene looks quite differently.
Is there any way to work around this?

A pink cube on top of a grey one.

With EffectComposer
![Screenshot 2022-11-01 210335](https://user-images.githubusercontent.com/20047687/199329319-6b40244d-4d25-4316-8bd9-71a993bbdb91.png)

Without EffectComposer
![Screenshot 2022-11-01 210352](https://user-images.githubusercontent.com/20047687/199329327-7c98d9d8-8174-45e3-ac76-7e1a99c4821f.png)
 
### To Reproduce

https://codesandbox.io/s/post-processing-and-layers-forked-4p2czd

### Expected behavior

Normal Blending with or without EffectComposer should look the same.

### Library versions  / OS used

 - Three: 146
 - Post Processing: 6.29.1
 - Windows, Mac, iOS, Android

**Comment by nz303** [comment]
Thank you - is there a way to render "incorrectly" when using postprocessing so that both render pathes look the same?

**Comment by vanruesc** [comment]
I don't think so. The built-in materials in `three` only convert colors to sRGB inside the shader.s when rendering to the canvas. There is currently no way to force `three` to do this when rendering to a render target which would be necesssary to emulate the incorrect output.

**Comment by nz303** [comment]
ok, got it - thank you very much vanruesc.
