### ISSUE TITLE
FXAA conflicts with DOF?

### ISSUE THREAD

**Issue by jcyuan** [pmndrs/postprocessing#422]
if I enable both FXAA and DOF, DOF not work...
and if i disable FXAA, DOF works fine...

bug? or I missed something?

**Comment by vanruesc** [comment]
Make sure you're setting things up correctly. The `DepthOfFieldEffect` expects a `Camera` as the first argument:
```js
new DepthOfFieldEffect(camera, options);
```

Merging DoF with FXAA will probably produce undesired artifacts, so I'd recommend first running FXAA in its own pass and then applying other effect in another pass.

**Comment by jcyuan** [comment]
> Make sure you're setting things up correctly. The `DepthOfFieldEffect` expects a `Camera` as the first argument:
> 
> ```js
> new DepthOfFieldEffect(camera, options);
> ```
> 
> Merging DoF with FXAA will probably produce undesired artifacts, so I'd recommend first running FXAA in its own pass and then applying other effect in another pass.

ahhh, got it.
yes, i put all efx into 1 pass.

and just tried now to put fxaa into a single pass to seperate from others, now all works as expected!
thanks so much.

**Comment by jcyuan** [comment]
ahh sorry, btw i have a question, usually FXAA should go which phase? after all effects or before?
for example, fxaa -> bloom, or bloom -> fxaa?
thanks.

**Comment by vanruesc** [comment]
There's no hard rule for this, but I'd recommend applying AA first, just like MSAA. Then the subsequent passes can work with the antialiased image. However, some effects may produce aliasing artifacts themselves so it can also make sense to apply AA at a later stage depending on the situation.

**Comment by jcyuan** [comment]
> There's no hard rule for this, but I'd recommend applying AA first, just like MSAA. Then the subsequent passes can work with the antialiased image. However, some effects may produce aliasing artifacts themselves so it can also make sense to apply AA at a later stage depending on the situation.

ok, makes sense! 👍 thank you.
