### ISSUE TITLE
Depth buffer issue when using DepthOfFieldEffect

### ISSUE THREAD

**Issue by hybridherbst** [pmndrs/postprocessing#426]
### Description of the bug

Follow-up to #420.
By using `dofEffect.circleOfConfusionMaterial.adoptCameraSettings` and `worldFocusDistance`, I was able to get a dynamic target to change the focus. I got it to match up / work in @vanruesc's [sandbox](https://codesandbox.io/s/gifted-forest-ssbdry?file=/src/App.js). 

However, I still don't get it to work elsewhere...

For me it looks like the depth buffer is in a wrong format, and that the calculation to go from linearized near/far values to world distances and vice versa doesn't match some setting here. I checked that we're not using logarithmic depth.

Maybe these images of expected and not expected cases help:
In the below images, 
- the textured plane is cut off by near and far clip planes of 1 and 10
- the white cube is the focus target - placed at 1, 10, ~5.5 and ~2.5

✔️ **Target at near clip plane - as expected: near clip plane is in focus**
![20221116-232215_chrome](https://user-images.githubusercontent.com/2693840/202307408-398cfdb5-ee68-4875-9202-57d73b00a5ab.jpg)

✔️ **Target at far clip plane - as expected: far clip plane is in focus**
![20221116-232224_chrome](https://user-images.githubusercontent.com/2693840/202307700-a1ebe7b3-ba82-41a1-a35b-337fcfc1ba99.png)

❌ **Target at center between near and far - not expected: focus is too close**
![20221116-232232_chrome](https://user-images.githubusercontent.com/2693840/202307715-de19a30a-79df-4bee-8129-970c9c045328.jpg)

❌ **Target at 1/4 between near and far - not expected: focus is too close**
![20221116-232236_chrome](https://user-images.githubusercontent.com/2693840/202307734-cf3da971-83ff-48f1-97e1-37d2ca352651.jpg)

So there seems to be some nonlinearity going on, but I have no idea why.

### To Reproduce

I'm unfortunately unsure how to reproduce / what's wrong in this setup so far. Happy to answer any questions to hopefully figure out what I'm doing wrong.

### Expected behavior

Ability to set the worldFocusDistance and get that distance in focus.

### Screenshots

see above

### Library versions used

 - Three: 0.145.4
 - Post Processing: 6.29.1

### Desktop

 - OS: Windows 10 and 11
 - Browser Chrome
 - Graphics hardware: RTX 2070 Max-Q and RTX 3070

**Comment by vanruesc** [comment]
Thanks for the screenshots :+1: 

How are you setting the `worldFocusDistance`? You'd want to set this to the distance from the camera to the cube. Alternatively, try setting `dofEffect.target` to `cube.position`;

**Comment by hybridherbst** [comment]
(my mistake convoluting R3F and three here, of course it's vanilla...)

Yes, this distance is the world distance from the camera to the cube. Also logged these values and made sure they match up with what I'd expect (e.g. in screenshots 2 and 3 the `worldFocusDistance` values logged are 5.5 and 2.5).

I get the same behaviour when using `dofEffect.target = cube.position`.
(side note, for that to work the cube must be a at sceen root / must not be transformed by it's parents if I'm not mistaken which I made sure of).

**Comment by vanruesc** [comment]
Strange.. I'll take a closer look this weekend.

> side note, for that to work the cube must be a at sceen root / must not be transformed by it's parents if I'm not mistaken which I made sure of

Thanks for pointing that out. The implementation currently doesn't use `getWorldPosition` which is a bug.

> For low near clip values (e.g. 0.01) I only get any focus when the target is at far clip distance, and basically all other target distances result in focus planes very close to the near clip plane.

Well, the shader does linearize depth, so this sounds like the camera settings aren't being set correctly for some reason.

**Comment by hybridherbst** [comment]
Thanks!

Right now I'm literally calling this
```
        setInterval(() => {

            dof.circleOfConfusionMaterial.adoptCameraSettings(camera);
            dof.target = targetObject.position;
            
        }, 50);
        ```
to ensure for now not messing up any timing here and that the right camera values are used. (Of course tried without that as well),

What's weird is that it does seem to work for "target distance == near clip" and "target distance == far clip" but nothing inbetween.

**Comment by hybridherbst** [comment]
Hi again! Were you by any chance able to look into the issue @vanruesc? Thanks!

**Comment by vanruesc** [comment]
Sorry, I've been too busy to get back to this. However, I was able to confirm that [viewZToOrthographicDepth](https://github.com/pmndrs/postprocessing/blob/64d2829f014cfec97a46bf3c109f3abc55af0715/src/utils/viewZToOrthographicDepth.js) returns correct values.

> I got it to match up / work in @vanruesc's [sandbox](https://codesandbox.io/s/gifted-forest-ssbdry?file=/src/App.js).
> However, I still don't get it to work elsewhere...

Any chance you could provide a failing example with code for me to look at?

**Comment by optimus007** [comment]
@hybridherbst does [this sandbox](https://codesandbox.io/s/dof-focus-slide-test-0ol0vo?file=/src/App.js) or video demonstrate the same issue you are talking about ?



https://user-images.githubusercontent.com/6885294/204822593-cee0b9d4-25a2-4f03-b472-fb0fc02db443.mp4

**Comment by vanruesc** [comment]
@optimus007 Thanks for the sandbox! The unexpected behaviour that can be observed when the target is off-center has to do with perspective projection. The object would probably remain in focus at all times with an orthographic camera. The effect translates the world distance to a linear, orthographic depth value which basically counters the perspective projection. I wonder if we could use perspective depth instead :thinking: 

Right now, I'm busy with work and the v7 redesign. I'll eventually get to the `DepthOfFieldEffect`.

@hybridherbst Does your project use logarithmic depth? That would explain why you're only able to focus objects close to the near and far planes.

**Comment by vanruesc** [comment]
The expected behaviour described in this ticket would be achieved by calculating the distance from individual fragments to the camera instead of using the scene depth. This would result in a spherical focus field around the camera instead of a box-like field between the near and far plane.

I don't plan on changing the current CoC implementation in `postprocessing` v6, but the new implementation in v7 will use the distance-based approach.

Closing this in favor of #569.
