### ISSUE TITLE
depth problem without EffectPass (only render pass)

### ISSUE THREAD

**Issue by Suprhimp** [pmndrs/postprocessing#427]
Hi,

When I imported and render my gltf models with postprocessing. It occurs depth probelm.

when I use with three js mesh, (with handmade mesh from geometry box) it works well. but 

When I import model, it render wrong. should I use at least one EffectPass to use postprocessing?

I need it because of user can select, deselect postprocessor.

I'll link with my [codesandbox](https://codesandbox.io/s/smoosh-violet-gi40tn?file=/src/App.ts).

Thanks!

**Comment by vanruesc** [comment]
If you use a single `RenderPass`, it will render directly to the canvas which has no depth buffer in your setup.

I'd recommend using a `CopyPass` after the `RenderPass` to render the correct image to screen. You could also enable the depth buffer on the canvas instead and not use an additional copy pass, but then there's a chance that transparent objects will look different with and without post effects.

**Comment by Suprhimp** [comment]
Thanks for the answer. I've met other problem and I will post that in other issue :)

I handled this with adding `this.composer.addPass(new CopyPass());`
