### ISSUE TITLE
How to adjust parameters to solve SSAOEffect graininess

### ISSUE THREAD

**Issue by shirlyyang-tcc** [pmndrs/postprocessing#432]
I am using ssao effect in my project and find the output with heavy graininess. Then I try to adjust the parameters,either lost details or still graininess. So i want to know how to adjust parameters to make the shadow looks natural? 
example below:
https://codesandbox.io/s/funny-rain-mlc1cu?file=/src/App.js

**Comment by shirlyyang-tcc** [comment]
solved

**Comment by vanruesc** [comment]
The current SSAO implementation doesn't support denoising. There are plans to replace the effect with a better implementation. For now, the only way to reduce the graininess is to adjust the resolution and sample count.
