### ISSUE TITLE
import 'postprocessing'  cause 404 error on next js

### ISSUE THREAD

**Issue by Suprhimp** [pmndrs/postprocessing#434]
Import cause 404 error in server side render(next js)

When i run in local it's run very well but since I deploy with vercel and next js.

Just when I use 

`composer = new EffectComposer(renderer, {});`

cause this  symptom..
<img width="1718" alt="스크린샷 2022-11-30 오후 3 52 21" src="https://user-images.githubusercontent.com/73486185/204727747-598724a4-5c68-4b7a-a447-05a458ac3cb5.png">

please help...

env:
    "postprocessing": "^6.29.1",
    "react": "18.2.0",
    "next": "12.2.0",
    "three": "^0.147.0",

**Comment by Suprhimp** [comment]
I solved with this way but please check if it is okay..

First I downloaded the postprocessing.js from node module postprocess build.

I put that file on my local path  and imported with `import * as POSTPROCESS from ./postprocessing` , 

I checked the error message with all lines that `require('three')` so I have to change the `require('three')`
to `THREE` with `import * as THREE from 'three';`

I checked that it solved the 404 error.

But In this way, `cocMaterial` in `DepthOfFieldEffect` is not work. I mean the changing world distance is not working..

**Comment by vanruesc** [comment]
Hi,

this should just work out of the box if you're using ESM modules correctly, e.g. via `import xxx from "xxx"`. The 404 errors are probably coming from those `require('xyz')` lines and it's unlikely that the `postprocessing` package is causing this.

> First I downloaded the postprocessing.js from node module postprocess build.

That's not a good idea. Why don't you use `import { EffectComposer } from "postprocessing";`? I'm not familiar with next.js, but this looks like a bundler misconfiguration issue.

**Comment by Suprhimp** [comment]
I tried that `import { EffectComposer } from "postprocessing";`
But it didn’t work neihter

**Comment by CodyJasonBennett** [comment]
This has nothing to do with the postprocessing library and entirely your usage of the file-based-routing of Nextjs. Please see its [docs](https://nextjs.org/docs/getting-started) and [basic routing](https://nextjs.org/docs/basic-features/pages).

For how to include three.js in a React app see:
 - imperatively via hooks: https://codesandbox.io/s/react-three-1l5oj
 - declaratively via a renderer: https://codesandbox.io/s/react-three-fiber-f78cg

If you need further help, ask in https://discord.gg/poimandres, but please don't resort to issues unless you're describing a feature request or bug of a library.
