### ISSUE TITLE
Bloom doesn't respond to MeshStandardMaterial .emissiveIntensity Float and .emissive Color values higher than 1 in linear space

### ISSUE THREAD

**Issue by ROBYER1** [pmndrs/postprocessing#439]
### Description of the bug

Using linear colour space, I was testing out emission values in a Three.js scene with the Bloom pass and noticed that making the MeshStandardMaterial .emissiveIntensity Float and .emissive Color values higher than 1 doesn't make them respond any differently to the Threshold value of Bloom Pass despite being set to 100 and RGB(0,200,0) respectively.

### To Reproduce

Make a three.js project with some emissive meshes in it, one set of emissive materials set their MeshStandardMaterial .emissiveIntensity Float to 1 and .emissive Color value to THREE.RGB(0,1,0) and then make another mesh with a different emissive material on with much higher values like MeshStandardMaterial .emissiveIntensity Float 100 and .emissive Color value THREE.RGB(0,200,0).

Add Bloom pass as per the examples here or use the sample demo project below where you can see the red circled large green rectangle is the console.log outputted material using mesh in the scene that has the higher 100 intensity and 200 RGB colour values, yet using the threshold slider doesn't make it cause higher bloom response vs the other meshes in the scene
![image](https://user-images.githubusercontent.com/10745594/208910431-8076120f-8b2e-4aee-85c8-33124b3a3770.png)

Glitch example: https://round-twisty-cyclamen.glitch.me/
Editable glitch project to Remix: https://glitch.com/edit/#!/round-twisty-cyclamen?path=README.md%3A1%3A0

### Expected behavior

MeshStandardMaterial .emissiveIntensity Float and .emissive Color values higher than 1 in linear colour space should have increased bloom due to having higher values than 0-1.

### Library versions used

 - "@types/three": "0.146.0",
 - "postprocessing": "^6.29.1"
 - Needle Tools Engine 2.54.2-pre + Unity 2022.1.23f1

### Desktop

 - Windows 11
 - Chrome  108.0.5359.125
 - Nvidia 2070 Max-Q Design in HP Z Book Laptop

**Comment by ROBYER1** [comment]
Sandbox example here also, the cubes start at emission strength 0.5, 1.0, 50, 100 respectively, you can use the GUI slider to slide the threshold of bloom along to see that the 1, 50 and 100 emission strength values seem to be clamped instead of using their HDR values. The 0.5 emission strength does react to the threshold when it is massively boosted so it seems the values are clamped from 0-1 for emission strength instead of using their full HDR/Linear range of values?

https://codesandbox.io/s/modest-dijkstra-udhiik?file=/src/App.js

![image](https://user-images.githubusercontent.com/10745594/209130953-bc0421bf-80d6-4a24-a383-122522355e2a.png)

**Comment by vanruesc** [comment]
High precison frame buffers are required to store colors that exceed [0, 1]. I'd also recommend enabling `mipmapBlur` on the `BloomEffect` to use the new mipmap bloom:

https://codesandbox.io/s/optimistic-chatterjee-ek41w0

**Comment by ROBYER1** [comment]
Closing this as the fix is as suggested to use half float type in the composer, thanks for the repro sent back - is it possible to add this to the samples or at least a mention of it for users? Would be useful if it was in the bloom sample 👍

```
  const composer = new EffectComposer(renderer, {
        frameBufferType: HalfFloatType
    });
```

**Comment by vanruesc** [comment]
> I can see it mentioned on the npm repo

I've added the information about HDR workflows and high precision buffers back to the readme until the new manual is ready.
