### ISSUE TITLE
DepthOfField effect not focusing with logarithmDepthBuffer

### ISSUE THREAD

**Issue by seo-rii** [pmndrs/postprocessing#445]
### Description of the bug

DepthOfField effect is not focusing object when I turned logarithmDepthBuffer option to true.

### To Reproduce

This is a link of example of react-three-fiber using DepthOfField effect.
https://codesandbox.io/s/bst0cy

And this is a link that only changed option logarithmDepthBuffer to true. Everything looks blurry.
https://codesandbox.io/s/monitors-forked-pl44hr?file=/src/App.js

### Expected behavior

Blur effect should focus target object.

### Screenshots

Without logarithmDepthBuffer
![image](https://user-images.githubusercontent.com/48939845/215334647-94e41bd2-2d40-40d2-b0b9-fa9a3cc0f8ff.png)

With logarithmDepthBuffer
![image](https://user-images.githubusercontent.com/48939845/215334619-9ffaf5f4-0ab1-4a00-bc03-337779769a38.png)

### Library versions used

 - Three: 0.148.0
 - Post Processing: 6.29.3

### Desktop

 - OS: Windows
 - Browser: Chrome latest (stable)
 - Graphics hardware: NVIDIA

**Comment by vanruesc** [comment]
`logarithmicDepthBuffer` is currently not supported and I'm not sure how difficult it would be to add support. Simply converting a log depth texture to linear depth defeats the purpose of encoding it in the first place, so depth values would probably need to be decoded on the fly inside the shaders on each read.

Let's keep this open as a feature request.

**Comment by vanruesc** [comment]
I've added this feature to the roadmap (#279).
