### ISSUE TITLE
RenderPass Apparent Depth Issue

### ISSUE THREAD

**Issue by sciencecompliance** [pmndrs/postprocessing#446]
I'm having some trouble with `RenderPass` apparently not respecting depth, render order, or something else in some cases unless I also add an `EffectPass` to the `EffectComposer` object after adding the render pass.  The effect pass can have an empty constructor and fix the problem, but it is still needed.  I am currently trying to optimize the experience for users with lower-end / older hardware, and it would be desirable to eliminate the effect pass entirely because I do notice a difference in GPU utilization (where I am currently bottlenecked) when I do not add it to the composer (even with an empty constructor).

I do not have a reproduction of the issue available to view currently, but I can share relevant code and some images of what's going on.  Here are the specs of the systems incurring this issue:

Operating Systems: `Windows 10`
Graphics Cards: `Nvidia RTX 3080`, `AMD FirePro W5130M`, `Intel HD Graphics 530`
Browsers:  `Microsoft Edge, v. 109.0.1518.70`, `Chrome, v. 109.0.5414.120`, `Firefox, v. 109.0.1`
Three.js version: `142`
postprocessing version: `v6.29.1 build Thu Oct 27 2022`

Image of the issue with no `EffectPass`:
Note that the planet is occluding the stars, just not the ring.  There is also a sprite representing the sun (out of frame in the image) that the planet's body also does not occlude properly (which is much deeper in the scene--about 2 orders of magnitude further in the scene using a linear scale than the far edge of the ring).

![saturn_depth_issue](https://user-images.githubusercontent.com/51130589/216201929-a5be3c30-067c-40a1-8962-d021a7bb6ee7.png)

After including `EffectPass` with an empty constructor:
(Note that adding the effect pass also seems to resolve some aliasing issues, probably most noticeable around the horizon)

![saturn_issue_resolved](https://user-images.githubusercontent.com/51130589/216202135-4fecf276-2006-4c34-aeae-b2037fb797e8.png)

Here is the code involved in setting up the three.js `WebGLRenderer` and then the `EffectComposer` (and passes):

Instantiating the renderer:
```js
// Create renderer and append canvas to DOM
const renderer = new THREE.WebGLRenderer({
    antialias: false,
    stencil: false,
    alpha: true,
    depth: false,
    logarithmicDepthBuffer: true,
});
renderer.shadowMap.enabled = true;
renderer.shadowMap.soft = true;
renderer.shadowMap.type = THREE.PCFSoftShadowMap;
renderer.physicallyCorrectLights = true;
```
Effect Composer instantiation:
```js
// Composer for post-processing effects
const composer = new EffectComposer( renderer, {multisampling: 4, frameBufferType: THREE.HalfFloatType} );
```
Render Pass and adding passes to composer:
```js
const renderPass = new RenderPass( scene, camera );
composer.addPass( renderPass );
composer.addPass( new EffectPass()); // <-- Trying to remove this line
```

Animation loop:
```js
// Animation loop function
function animate() {
    requestAnimationFrame( animate );
    composer.render();
}
```

FYI.  The code shown is spread among different files with a lot of other code in between that has been left out.  This is the only code that seemed relevant by referencing the offending objects, though (with the exception of renderer sizing / resizing).

**Comment by vanruesc** [comment]
The RenderPass will render to the canvas if it's the last (or only) enabled pass in the chain. If this is intended, you should enable the depth buffer when you instantiate the renderer:

```
const renderer = new THREE.WebGLRenderer({
    antialias: false,
    stencil: false,
    alpha: true,
    depth: true,
});
```

Also, `logarithmicDepthBuffer` is not supported and will lead to unexpected results when using depth-based effects.

Please note that rendering directly to screen/canvas may produce incorrect results compared to rendering to texture and then copying to screen when blending transparent objects. Instead of using an empty EffectPass you could use a CopyPass as a default setup but the performance impact would be the same.

**Comment by vanruesc** [comment]
Closing as this seems to be resolved.
