### ISSUE TITLE
ChromaticAberrationEffect and DotScreenEffect support for selection class.

### ISSUE THREAD

**Issue by wallysaurus** [pmndrs/postprocessing#447]
### Is your feature request related to a problem?

I turned towards this library after fooling around with the postprocessing effects in three.js's addons. Camera layers provided somewhat of a patch-up job for what I'm trying to achieve, but there were a lot of visual bugs specifically around how models with postprocessing would look in terms of depth with others.

### Describe the solution you'd like

I was told by people in the support discord that this library had better support for per-mesh selection, but after investigation found that ChromaticAberrationEffect and DotScreenEffect didn't implement/extend the selection class and was looking for support. I also heard it was relatively easy to do for other effects in the past, like SSR.

### Describe alternatives you've considered

![image](https://user-images.githubusercontent.com/69739715/216849923-7eef43fe-2ef5-4e77-9fdc-7382c81fb545.png)
Shown above was my attempt at achieving what I wanted using the shaders provided by three.js addons and camera layers. I'm hoping to avoid the weird dept overlap shown.

**Comment by vanruesc** [comment]
Right, only some effects currently support selections. There are plans to support selections on a higher level with the v7 redesign using MRT, but it's still in the works.

**Comment by vanruesc** [comment]
Closing this. Wider support for selections is on the roadmap.
