### ISSUE TITLE
Class 'Timer' incorrectly implements interface 'EventListenerObject'.

### ISSUE THREAD

**Issue by MajorMeerkatThe3rd** [pmndrs/postprocessing#449]
I found a small issue in your declarations file. I only go to this by accident. 
In the class Timer you seem to be missing the implementation of `handleEvent`.
Probably not a big issue, I just found it because my tsconfig file wasn't configured correctly.

There are the errors that I found there:
`error TS2420: Class 'Timer' incorrectly implements interface 'EventListenerObject'.`
`Property 'handleEvent' is missing in type 'Timer' but required in type 'EventListenerObject'.`

**Comment by vanruesc** [comment]
Thanks for the report! I'll include a fix in the next release.
