### ISSUE TITLE
embedding an EffectComposer in a RenderTexture

### ISSUE THREAD

**Issue by phi2LchambreG** [pmndrs/postprocessing#462]
is it possible for an `EffectComposer` to render inside a `RenderTexture` (or `createPortal`) and not directly to screen?
- using `createPortal`, see https://codesandbox.io/s/gracious-elion-s1bnwd
- using `RenderTexture`, see https://codesandbox.io/s/jovial-diffie-r39zw7
  - without `EffectComposer`: 

    <img width="420" src="https://user-images.githubusercontent.com/123647414/225288818-e2a95ea7-9917-464a-9c2e-bc879d959c8c.png"/>
  
  - with `EffectComposer`: 

    <img width="420" src="https://user-images.githubusercontent.com/123647414/225289198-2b649f4d-fbcc-47d8-a353-f326e094e4f7.png" />

(not sure if it's more related to `RenderTexture` or `EffectComposer` so I'll post this at both https://github.com/pmndrs/postprocessing/ and https://github.com/pmndrs/drei)

**Comment by vanruesc** [comment]
You can use a [CopyPass](https://pmndrs.github.io/postprocessing/public/docs/class/src/passes/CopyPass.js~CopyPass.html) with a custom render texture / buffer (`WebGLRenderTarget`) that you'd like to render to. Make sure this is the last pass in your effect chain and set [composer.autoRenderToScreen](https://pmndrs.github.io/postprocessing/public/docs/class/src/core/EffectComposer.js~EffectComposer.html#instance-member-autoRenderToScreen) to `false`.

**Comment by phi2LchambreG** [comment]
thanks a lot! I've updated the sandbox but I'm still missing something: https://codesandbox.io/s/gracious-elion-s1bnwd
(it only refreshes "on demand", when I update code on the left...)

![image](https://user-images.githubusercontent.com/123647414/225597901-4deaeacf-02ac-4f37-bbcb-f8ebd5133904.png)
