### ISSUE TITLE
Combining two outline effects

### ISSUE THREAD

**Issue by rospuye** [pmndrs/postprocessing#464]
Hey @vanruesc! Thanks for the awesome library! :)

I noticed something while working with the outline effect. I'm not 100% sure if this is an actual bug or if I haven't found the right configuration for the effect composer, but after playing with different options I haven't been able to find a solution to my problem.

### Description of the bug

I'm trying to combine two outline effects that serve different purposes (one for selection and one for hover). The problem is that altering the selection for either of the outline effects affects the selection of the other one as well.

For example, if I select an object and get the red selection outline, that outline disappears as soon as the mouse stops hovering said object because the setting of the hover outline's selection to an empty array also affected the selection array for the selection outline.

I've tried exploring the outline effect attributes, I also tried to place the two outline effects on different effect passes, and I've tried to juggle two effect composers as well, all without success.

### To Reproduce

I built a [demo sandbox](https://codesandbox.io/s/outlineexperiment-25vlw0?file=/src/App.js) to illustrate the problem.

### Expected behavior

In the demo sandbox, I have a selection outline effect (in red) that should show up according to the selection or de-selection of different objects on the scene, and I have a hover selection effect (in white) that, as the name suggests, should appear when I hover over the same objects with the mouse, and disappear when those objects are no longer being hovered. The hover outline should only appear when the selection outline is not already present for one given object.

### Library versions used

 - Three: 0.146.0
 - Post Processing: 6.20.1
 - Spatial Controls: 5.0.8

### Desktop

 - OS: Ubuntu
 - Browser: Chrome 110.0.5481.100
 - Graphics hardware: NVIDIA

**Comment by vanruesc** [comment]
Hi,

`OutlineEffect` uses a [Selection](https://github.com/pmndrs/postprocessing/blob/f8ed90635ee6710744cc0f38811fc00ce873a450/src/core/Selection.js) which relies on render layers. If you create multiple outline effects, they'll all use the same render layer (10) by default. To prevent the effects from interfering with each other, change the render layer of one of them:

```js
outlineEffect.selection.layer = 11;
```

**Comment by rospuye** [comment]
You're right, it worked! Thank you for your help :)
