### ISSUE TITLE
SSAO issue when using a ShaderPass first

### ISSUE THREAD

**Issue by thibka** [pmndrs/postprocessing#466]
Hi!

When adding a ShaderPass (or an EffectPass) at the beginning of my postprocessing pipeline, the SSAOEffect is broken and produces weird results. 

Here's a demo, where the ssao effect is using BlendFunction.NORMAL for easier debugging, and you can enable/disable the shaderPass to see the issue:
https://codesandbox.io/s/charming-hodgkin-xsnj0r?file=/src/App.js

(The reason I'm using a ShaderPass here is that I wanted to use a SavePass right after to save its content, so that I could use it as a texture in my app)

Am I making a mistake here or could it be a bug?

Thanks!

EDIT: the same kind of issue occurs if I use `DepthOfFieldEffect` instead of `SSAOEffect` (the whole screen is blurred) so it looks like the depth info is lost. But why? 🤔

**Comment by vanruesc** [comment]
Likely related to #225 which will be fixed by the v7 redesign.
