### ISSUE TITLE
SelectiveBloom affects the background of the scene

### ISSUE THREAD

**Issue by thibka** [pmndrs/postprocessing#468]
Hi, 

### Description of the bug

The SelectiveBloom effect affects the background of the scene.

### To Reproduce

Here's a minimal demo
https://codesandbox.io/s/hungry-gould-mx2b4l?file=/src/App.js

### Expected behavior

Selective Bloom should only be applied to the array of objects specified with
`selectiveBloomEffect.selection.set(selectionArray);`

**Comment by vanruesc** [comment]
Selective bloom has a setting to [ignore the background](https://pmndrs.github.io/postprocessing/public/docs/class/src/effects/SelectiveBloomEffect.js~SelectiveBloomEffect.html#instance-get-ignoreBackground).

**Comment by thibka** [comment]
Oh, wonderful, I didn't know about that! 
I don't know if it's the common approach for selective bloom, but I feel like it would make sense to have it set to `true` by default, though. 🤔 
Anyway, thank you so much! ❤️
