### ISSUE TITLE
SelectiveBloomEffect doesn't work with Points

### ISSUE THREAD

**Issue by Beilinson** [pmndrs/postprocessing#469]
### Description of the bug

SelectiveBloomEffect doesn't work with Points

### To Reproduce

Create a Scene with some Points Geometry, add the Points to the SelectiveBloomEffect selection and render.

### Expected behavior

Selection of points will work just like Meshes.

### Screenshots

Using regular bloom effect:
![image](https://user-images.githubusercontent.com/54665621/228925369-d0425a14-6868-41f1-bca7-f9e24134935c.png)

Using selective bloom effect with a selection of all points geometries in the scene:
![image](https://user-images.githubusercontent.com/54665621/228926358-88d84373-b601-42a0-8ffe-a79c2ddc5695.png)

### Library versions used

 - Three: [e.g. 0.150.0]
 - Post Processing: [e.g. 6.30.1]

### Desktop

 - OS: Windows
 - Browser: Chrome Latest
 - Graphics hardware: NVIDIA/Intel UHD

**Comment by vanruesc** [comment]
The current implementation of `SelectiveBloomEffect`  uses depth to discard pixels of objects that are not selected. This can be inaccurate and may not work at all if the selected object doesn't write depth. Point clouds are probably the worst case scenario for this masking technique.

If you can use high precison frame buffers with `frameBufferType: HalfFloatType` (see readme), you could try using the basic `BloomEffect` with a luminance threshold of `1.0`. Points that should bloom could then use color values greater than 1.

**Comment by Beilinson** [comment]
Thanks for all the amazing work you're doing!

Could the implementation change to support such a use case in v7+?

**Comment by vanruesc** [comment]
> Could the implementation change to support such a use case in v7+?

Yes, there are plans to support rendering selected objects to a separate buffer during the main render step via MRT while respecting depth and taking MSAA into account. Any other masking technique based on depth or color is subject to artifacting.

**Comment by JixiongXiao** [comment]
> > Could the implementation change to support such a use case in v7+?
> 
> Yes, there are plans to support rendering selected objects to a separate buffer during the main render step via MRT while respecting depth and taking MSAA into account. Any other masking technique based on depth or color is subject to artifacting.

when I set renderer.logarithmicDepthBuffer = true, the selectedBloomEffect doesn't work as well. Is there any way to fix it?

**Comment by vanruesc** [comment]
@JixiongXiao That should be fixed by now.

Closing this since selective effects are planned to be improved as part of v7.
