### ISSUE TITLE
A-Frame error

### ISSUE THREAD

**Issue by iamkim17** [pmndrs/postprocessing#471]
### Description of the bug
using the example in the Wiki -> A-Frame

### To Reproduce
Go to this example
https://jsfiddle.net/pa9jyd45/

### Expected behavior
Postprocessing in A-Frame should work

### Screenshots
https://imgur.com/a/WPKwVu4

### Library versions used

 - Post Processing: postprocessing v6.30.2

### Desktop

 - OS: Windows
 - Browser Chrome 111.0.5563.147 (Official Build) (64-bit)
 - Graphics hardware: Nvidia 2080

**Comment by vanruesc** [comment]
Thanks for the report!

Fixed fiddle: https://jsfiddle.net/Lhtag32n/

**Comment by iamkim17** [comment]
Thank you @vanruesc ! I can confirm that the A-Frame demo is fixed!
