### ISSUE TITLE
OutlinePass doesn't have setRenderer function but EffectComposer demands it

### ISSUE THREAD

**Issue by KarthikHebbarMN** [pmndrs/postprocessing#472]
Getting setRenderer is not a function when adding OutLinePass to EffectComposer's passes. 

Added a EffectComposer to the scene using 
`const composer = new POSTPROCESSING.EffectComposer(renderer)`

Created Instance of OutlinePass
```
import { OutlinePass } from 'three/addons/postprocessing/OutlinePass.js'; 
 
let outlinePass = new OutlinePass(new THREE.Vector2(window.innerWidth, window.innerHeight), scene, camera);
//camera is a perspectiveCamera
//scene is initialized 
composer.addPass( outlinePass );
```

I get the following error 

> postprocessing.esm.js:7726 Uncaught (in promise) TypeError: pass.setRenderer is not a function
    at EffectComposer.addPass (postprocessing.esm.js:7726:10)

And when I look up at line 7726 of EffectComposer this is found 
```
 addPass(pass, index) {
    const passes = this.passes;
    const renderer = this.renderer;
    const drawingBufferSize = renderer.getDrawingBufferSize(new Vector217());
    const alpha = renderer.getContext().getContextAttributes().alpha;
    const frameBufferType = this.inputBuffer.texture.type;
    pass.setRenderer(renderer); *** <----
    pass.setSize(drawingBufferSize.width, drawingBufferSize.height);
```

Using
 - Three: 0.150.1
 - Post Processing: ^6.30.1

Environment (not sure if its relevant to this error)
 - OS: Win
 - Browser Chrome
 - Graphics hardware: Nvidia RTX 2060

**Comment by vanruesc** [comment]
This library is not compatible with the passes from three.js.

**Comment by KarthikHebbarMN** [comment]
Then any idea what the workaround is ?

**Comment by vanruesc** [comment]
You could either use the `OutlineEffect` that is included in the `postprocessing` package or use three's postprocessing stack instead.

**Comment by KarthikHebbarMN** [comment]
Thanks,

Resolved by using OutlineEffect from 'postprocessing' package. 

But the performance on mobile is very bad for the same, any order I should be passing it in. ?

Will be closing this, as the issue is resolved, and the performance can be a different thread.
