### ISSUE TITLE
outline doesn't appear on model.

### ISSUE THREAD

**Issue by jomin398** [pmndrs/postprocessing#479]
I want to use bloom effect and outline effect at the same time.
But i tried that, outline doesn't appear on model.
How to fix it?
``` javascript

const outlineEffect = new OutlineEffect(scene, camera, {
      blendFunction: BlendFunction.SCREEN,
			edgeStrength: 10,
			height: 480,
      pulseSpeed: 0.0,
      visibleEdgeColor: 0x0,
      hiddenEdgeColor: 0x00ffffff,
      resolutionScale: 0.5,//0.5,
      usePatternTexture: false
});
const effectPass = new EffectPass(camera,
      smaaEffect,
      bloomEffect, //SelectiveBloomEffect
      outlineEffect);
//effectCompresser
FinalComp.addPass(effectPass);
```
### Library versions used
- Three: Latest
- Post Processing: Latest
### rendering at..
- Desktop: Windows
- Browser: Chrome Latest

**Comment by vanruesc** [comment]
The visible edge color is `0x0`. If you want black outline, set the `blendFunction` to `BlendFunction.ALPHA`.

**Comment by vanruesc** [comment]
Closing this as it seems to be resolved.
