### ISSUE TITLE
Use postprocessing's passes and Three's passes work together

### ISSUE THREAD

**Issue by johnnylc** [pmndrs/postprocessing#480]
We used to develop several customized effects using the THREE's EffectComposer, RenderPass, etc. When using postprocessing, THREE's passes are not compatible with this package. 
I tried to create EffectComposer from THREE and postprocessing seperately, and then add their own passes which does not work.
How to make the passes from postprocessing package and from THREE's  work together? 
Thanks.

**Comment by vanruesc** [comment]
> How to make the passes from postprocessing package and from THREE's work together?

Three's postprocessing passes are not compatible with this library. Please check the bug tracker for similar questions before opening a new one.

If you'd like to use custom passes that were written for three's postprocessing stack with this library, you'll need to adjust them according to the API of [this library](https://pmndrs.github.io/postprocessing/public/docs/class/src/passes/Pass.js~Pass.html).
