### ISSUE TITLE
Inconsistent / confusing DOF behavior

### ISSUE THREAD

**Issue by FractalHQ** [pmndrs/postprocessing#482]
Hey there!  I have a scene with a particle system and a floor.  I'm noticing that the DOF effect is creating strange shapes on far particles, but correctly blurring the near particles.

<img width="300" alt="Screenshot 2023-04-28 at 5 09 19 PM" src="https://user-images.githubusercontent.com/55504972/235254957-66830d3c-8e75-43cc-ad9b-4afa65dce60f.png">

It also seems to only work when the floor plane is behind the particles.

<details><summary>Video demonstration</summary>
<p>

https://user-images.githubusercontent.com/55504972/235255155-24714d92-3ba2-4291-b33b-c32ad4cc66c5.mp4

</p>
</details> 

I'm mostly hoping to better understand why this happening, and how I can influence the behavior.  Ideally, I'd like get the nice blur effect instead of the odd shape effect, and understand why DOF blur disappears when there is nothing behind the particles.

Any insight would be greatly appreciated!

**Comment by FractalHQ** [comment]
I seem to have solved the problem with the strange shape by disabling `depthWrite` on the particles material!

**Comment by FractalHQ** [comment]
Solved the other issue as well by adding `transparent` and `premultiplyAlpha` onto a back wall 👍🏽

**Comment by vanruesc** [comment]
There was a bug in DoF which may have caused this issue. It was fixed in #481, `postprocessing@6.31.0`.
