### ISSUE TITLE
With this error with Glow, does anyone know what the reason is in general? This error does not occur with the glow that comes with the three.js

### ISSUE THREAD

**Issue by WREQI** [pmndrs/postprocessing#484]
![image](https://user-images.githubusercontent.com/35467304/236371938-63c0f260-b8b0-4146-a812-28ff229093eb.png)
With this error with Glow, does anyone know what the reason is in general? This error does not occur with the glow that comes with the three.js

**Comment by vanruesc** [comment]
Well, that looks all sorts of broken. Could be a driver or hardware bug that's triggered by something that `postprocessing` does differently. But without _any_ details, I'm afraid it's impossible to investigate.

**Comment by vanruesc** [comment]
Closing this as it looks like a GPU hardware/driver issue.
