### ISSUE TITLE
"The requested module 'postprocessing' is a CommonJS module, which may not support all module.exports as named exports."

### ISSUE THREAD

**Issue by KeystoneScience** [pmndrs/postprocessing#485]
getting the following error:

SyntaxError: Named export 'BlendFunction' not found. The requested module 'postprocessing' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'postprocessing';
const { BlendFunction, BloomEffect, BrightnessContrastEffect, ChromaticAberrationEffect, ColorAverageEffect, ColorDepthEffect, DepthEffect, EffectComposer: EffectComposer$1, RenderPass, NormalPass, DepthDownsamplingPass, EffectPass, DepthOfFieldEffect, MaskFunction, DotScreenEffect, GlitchEffect, GlitchMode, GodRaysEffect, GridEffect, HueSaturationEffect, NoiseEffect, OutlineEffect, PixelationEffect, ScanlineEffect, SelectiveBloomEffect, SepiaEffect, SSAOEffect, SMAAEffect, TextureEffect, ToneMappingEffect, VignetteEffect, ShockWaveEffect, LUT3DEffect, TiltShiftEffect: TiltShiftEffect$1, Effect, EffectAttribute, DepthPickingPass, CopyPass } = pkg;

I am using Next.JS with tailwind, and have been searching for a few hours. Any advice? Thanks so much!

**Comment by Suprhimp** [comment]
Same error In next js ;(

**Comment by natibekele** [comment]
I was having this issue as well. I'm working around it right now by sticking to 2.8.3 from @Suprhimp's comment

**Comment by alvarosabu** [comment]
Any updates on this? I'm also having the issue on TresJS Nuxt module when using the `@tresjs/post-processing` package which uses this package under the hood.

**Comment by vanruesc** [comment]
I'll try changing the package type and exports this weekend.

Switching to `type: module` was something I wanted to do in v7 as it's technically a breaking change, but since bundlers are failing to load `postprocessing`, one could argue that it's a bug fix.

**Comment by vanruesc** [comment]
Should be fixed in `postprocessing@6.32.0`.

**Comment by alvarosabu** [comment]
Thanks a lot for you work 🙏🏻
