### ISSUE TITLE
Outline effect blends with background

### ISSUE THREAD

**Issue by MajorMeerkatThe3rd** [pmndrs/postprocessing#489]
### Description of the bug

When using the outline effect, the color is blended with the background. How can I avoid this?

### To Reproduce

Go to the outline demo and select a red color for the outline and position the model like this:
![image](https://github.com/pmndrs/postprocessing/assets/40572701/b01db3d4-52c9-4667-bbf6-7696479229fb)

**Comment by vanruesc** [comment]
This is the expected behaviour, assuming you're using the blend function `ADD` or `SCREEN`. I think what you want is `ALPHA`:

```js
const outlineEffect = new OutlineEffect(scene, camera, {
	blendFunction: BlendFunction.ALPHA,
	...
});
```

**Comment by MajorMeerkatThe3rd** [comment]
Thank you @vanruesc, this solved it for me!
