### ISSUE TITLE
SelectiveBloomEffect doesn't work when renderer.logarithmicDepthBuffer set true

### ISSUE THREAD

**Issue by JixiongXiao** [pmndrs/postprocessing#493]
### Description of the bug

SelectiveBloomEffect doesn't work when renderer.logarithmicDepthBuffer set true. 
While BloomEffect works. 

### To Reproduce

set webglRenderer.logarithmicDepthBuffer  as true and using selectiveBloomEffect

### Library versions used

 - Three: 0.143
 - Post Processing: 6.30.2

### Desktop

 - OS: Windos
 - Browser Chrome
 - Graphics hardware: NVIDIA 3050

**Comment by vanruesc** [comment]
Fixed in `postprocessing@6.31.1`.
