### ISSUE TITLE
Rendering glitches for examples with high consumption

### ISSUE THREAD

**Issue by MajorMeerkatThe3rd** [pmndrs/postprocessing#495]
### Description of the bug

When trying out the demos I noticed that sometimes I experience some glitches when moving the camera around. This seems to happen especially for examples with a higher resource consumption. It does not always happen, therefore I think there could be a small bug that is causing this. Maybe you have seen this issue before and know that it is something else.

Thank you!

### To Reproduce

Go to a demo like the SSAO and increase the Samples. Then move the camera around.

### Screenshots

I took a screenshot from my recording and added the recording itself.
![image](https://github.com/pmndrs/postprocessing/assets/40572701/01203b68-2195-41af-903c-3d90c4c8f9ce)
https://github.com/pmndrs/postprocessing/assets/40572701/05b2136c-a7f8-43ba-bdc6-05c7524854d4

### Desktop

 - OS: Windows
 - Browser: Chrome 114.0.5735.110
 - Graphics hardware: NVIDIA Quadro T2000

**Comment by vanruesc** [comment]
I have not seen those glitches before. Looks like screen tearing or some kind of frame refresh bug to me. I don't know what could be causing this though :thinking:

**Comment by MajorMeerkatThe3rd** [comment]
@vanruesc Thank you. I now noticed these issues on other sites as well, it seems that my GPU is dying...
Closing the issue!
