### ISSUE TITLE
Bloom based on emissive threshold and emissive map rather than (or in addition to luminance threshold)

### ISSUE THREAD

**Issue by lviggiani** [pmndrs/postprocessing#496]
Hi, I would like to achieve Bloom based on emissive value and emissive map rather than (or, even better, in addition to) luminanceThreshold.
Basically I'd like to get this:

![image](https://github.com/pmndrs/postprocessing/assets/139040/a3735742-4fce-426f-9ddd-694bfa55b486)

1. Bool on roof is based on luminance (as now)
2. Bool on car rear lights is based on emissive + emissive map 

I know that I could use a selective bloom and set luminance Threshold to 0 and apply to those objects only, but I'm looking for a solution that would base on emissive + map automatically rather than having to manually select objects. Also please note that my model is using an atlas material shared with other meshes whose emissive map part is black, so I cannot select objects basing on their material to move them to the selective bloom layer.
The image above comes from Blender Evee that is doing exaclty what I'm trying to achieve.
Thanks in andvance for any help!

**Comment by vanruesc** [comment]
Try this:

1. Enable [half float buffers](https://github.com/pmndrs/postprocessing#output-encoding) to store colors that exceed the [0, 1] range
2. Use the basic `BloomEffect` and set its `luminanceThreshold` to `1.0` (default smoothing should be fine)
3. Raise the `emissiveIntensity` of your model above `1.0`
4. Use a `ToneMappingEffect`, preferably with `ToneMappingMode.ACES_FILMIC`, to bring colors back to [0, 1]

**Comment by lviggiani** [comment]
It worked out of the box by enabling half float buffers, thank'you very much!
And now also I understand a bit better how it works. I thought that buffers already were able to handle values above 1 (or 255) but now also understand why by default it's using bytes as a "trade-off between hardware support, efficiency and quality" (I must have read the README more carefully before :) ).

![image](https://github.com/pmndrs/postprocessing/assets/139040/d2c32b70-aae2-4c80-ac93-69fa9e8cad1b)

![image](https://github.com/pmndrs/postprocessing/assets/139040/be3669ca-679b-4ec8-8403-59ab246658e7)

**Comment by vanruesc** [comment]
FYI: make sure to enable mipmap blur for faster and better bloom if you haven't already:

```js
const bloomEffect = new BloomEffect({
  mipmapBlur: true
})
```

**Comment by lviggiani** [comment]
Thanks for the hint! It looks much better now!

![image](https://github.com/pmndrs/postprocessing/assets/139040/0334e5e6-4d64-4819-a216-9672ef098dca)
