### ISSUE TITLE
TS7016: Could not find a declaration file for module 'postprocessing'.

### ISSUE THREAD

**Issue by amir-khoshbakht** [pmndrs/postprocessing#503]
just created an empty react project with typescript template.
when I import 'postprocessing' it throws an error.
VS Code does not show any errors, and even with ctrl+click, you can go to the library folder in the node module folder.

### To Reproduce

1- create an empty react project with typescript template:
yarn create react-app . --template typescript
2- import { BlendFunction } from 'postprocessing'

### Expected behavior
there should be no error.
The only way I found to silence this problem is to set the option **"noImplicitAny": false in tsconfig** in tsconfig.json

### Screenshots
![image](https://github.com/pmndrs/postprocessing/assets/68753961/21d0db13-c102-412a-acfc-9e83c5d4d341)

### Library versions used
`"postprocessing": "^6.32.0"`
`"three": "^0.153.0"`

### Desktop

 - OS: windows 10
 - Browser: Chrome Version 114.0.5735.134 (Official Build) (64-bit)
 - Graphics hardware: NVIDIA

**Comment by vanruesc** [comment]
That's surprising. Why is it using the old [main](https://github.com/pmndrs/postprocessing/blob/e3370c5609b5fd0867adb3360bd772a40e3e3098/package.json#L9) entry point and why does it ignore the [types](https://github.com/pmndrs/postprocessing/blob/e3370c5609b5fd0867adb3360bd772a40e3e3098/package.json#L11) field? It's fine if it wants to use the CommonJS entry point that badly, but why are the types completely ignored? :man_shrugging: 

What version of node.js are you using?

**Comment by vanruesc** [comment]
Can you also please check what happens when you edit `node_modules/postprocessing/package.json` and change `main` to `"./build/index.js"`?

**Comment by amir-khoshbakht** [comment]
> Can you also please check what happens when you edit `node_modules/postprocessing/package.json` and change `main` to `"./build/index.js"`?

same exact thing happens
![image](https://github.com/pmndrs/postprocessing/assets/68753961/b8bd2b41-83bc-46a3-ab48-4bd43c01245b)

**Comment by amir-khoshbakht** [comment]
> That's surprising. Why is it using the old [main](https://github.com/pmndrs/postprocessing/blob/e3370c5609b5fd0867adb3360bd772a40e3e3098/package.json#L9) entry point and why does it ignore the [types](https://github.com/pmndrs/postprocessing/blob/e3370c5609b5fd0867adb3360bd772a40e3e3098/package.json#L11) field? It's fine if it wants to use the CommonJS entry point that badly, but why are the types completely ignored? 🤷‍♂️
> 
> What version of node.js are you using?

node version : v18.16.0
dependency part of package.json:
```"dependencies": {
    "@react-three/drei": "^9.76.0",
    "@react-three/fiber": "^8.13.3",
    "@react-three/postprocessing": "^2.14.10",
    "@testing-library/jest-dom": "^5.14.1",
    "@testing-library/react": "^13.0.0",
    "@testing-library/user-event": "^13.2.1",
    "@types/jest": "^27.0.1",
    "@types/node": "^16.7.13",
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    "@types/three": "^0.152.1",
    "postprocessing": "^6.32.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "three": "^0.153.0",
    "typescript": "^4.4.2",
    "web-vitals": "^2.1.0"
  },


I am making a project based from a tutorial video. The video uses .js and I used .ts.
Do I have to do anything special to use this package? For example, installing the @type package ?

**Comment by vanruesc** [comment]
> Do I have to do anything special to use this package? For example, installing the @type package ?

The types are included in this package. Your build setup just isn't finding them for some reason.

Maybe this is an issue with your `tsconfig`. What `moduleResolution` strategy are you using? I think it should be set to `node`. And does your app also specify `"type": "module"` in its `package.json`?

**Comment by amir-khoshbakht** [comment]
> > Do I have to do anything special to use this package? For example, installing the @type package ?
> 
> The types are included in this package. Your build setup just isn't finding them for some reason.
> 
> Maybe this is an issue with your `tsconfig`. What `moduleResolution` strategy are you using? I think it should be set to `node`. And does your app also specify `"type": "module"` in its `package.json`?

By changing the value of moduleResolution from node to bundler, the error no longer occurs. But in this case, vscode shows this problem:

![image](https://github.com/pmndrs/postprocessing/assets/68753961/b97bb1ed-e0bb-4ca9-a667-ad19b294c721)


current tsconfig.json(default tsconfig from :yarn create react-app . --template typescript)
```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": [
    "src"
  ]
}

```

**Comment by vanruesc** [comment]
> By changing the value of moduleResolution from node to bundler, the error no longer occurs

The value `"bundler"` [doesn't exist for this setting](https://www.typescriptlang.org/tsconfig#moduleResolution) :thinking:

Please try removing the `"moduleResolution"` setting completely to check if that fixes it. The setting `"module": "esnext"` should automatically set the module resolution to `"nodenext"`.

**Comment by amir-khoshbakht** [comment]
> > By changing the value of moduleResolution from node to bundler, the error no longer occurs
> 
> The value `"bundler"` [doesn't exist for this setting](https://www.typescriptlang.org/tsconfig#moduleResolution) 🤔
> 
> Please try removing the `"moduleResolution"` setting completely to check if that fixes it. The setting `"module": "esnext"` should automatically set the module resolution to `"nodenext"`.

but its available in vscode intelligence:
![image](https://github.com/pmndrs/postprocessing/assets/68753961/4bb94565-3d24-4dfd-ba9e-e34245842b96)
also "bundler" is default value for react vite typescript project

also by removing the `"moduleResolution"` is set to the "classic" And many other imports also face problems. It is interesting that import of `"three"` does not face such problem in any case 
![image](https://github.com/pmndrs/postprocessing/assets/68753961/6b401c36-1d6a-457a-ab3f-bce4044909b5)

**Comment by amir-khoshbakht** [comment]
> > By changing the value of moduleResolution from node to bundler, the error no longer occurs
> 
> The value `"bundler"` [doesn't exist for this setting](https://www.typescriptlang.org/tsconfig#moduleResolution) 🤔
> 
> Please try removing the `"moduleResolution"` setting completely to check if that fixes it. The setting `"module": "esnext"` should automatically set the module resolution to `"nodenext"`.

https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#moduleresolution-bundler

**Comment by amir-khoshbakht** [comment]
@vanruesc by adding this option to tsconfig the error is gone . both in vscode and terminal:
`"allowImportingTsExtensions":true,`

**Comment by amir-khoshbakht** [comment]
@vanruesc found something . there is no such file "index.d.ts" in the package:
![image](https://github.com/pmndrs/postprocessing/assets/68753961/12cbc442-8c8d-44b1-80d0-25be7ac5444d)

**Comment by vanruesc** [comment]
I even checked the GitHub actions workflow to confirm whether the file was included in the package, but I didn't notice the incorrect file name :man_facepalming: 

Thanks for investigating! I'll push a fix in a bit.

**Comment by vanruesc** [comment]
Should be fixed in `postprocessing@6.32.1`.

**Comment by CodyJasonBennett** [comment]
FWIW https://arethetypeswrong.github.io and https://publint.dev provide a sanity check for both package config and output.

**Comment by vanruesc** [comment]
@CodyJasonBennett Thanks, thats useful :ok_hand:
