### ISSUE TITLE
SSAO is not working with three `0.153.0` on Android:Chrome

### ISSUE THREAD

**Issue by marwie** [pmndrs/postprocessing#506]
### Description of the bug

Running the SSAO sample on android chrome doesnt have any SSAO

### To Reproduce

1) Pull postprocessing package. I tested with c3ce388be247916437a314f17748a75329d65df1  

2) Modify hugo startup parameters to start on host ip address (so it can be opened via a phone in the same local network)
    `` "start": "hugo server -s manual -e development --bind=<your_ipv4> --baseURL=http://<your_ipv4>:1313",`` 

### Expected behavior

SSAO being rendered on android

### Screenshots

![image](https://github.com/pmndrs/postprocessing/assets/5083203/43c7f8ee-3cda-4183-a86a-ce44aaa8a17f)

Set intensity to maximum:

![image](https://github.com/pmndrs/postprocessing/assets/5083203/f525983b-b77d-428b-a0fa-e3fee5ab57ab)

### Library versions used

 - Three: 153
 - Post Processing: c3ce388be247916437a314f17748a75329d65df1  

### Mobile

 - Device: Pixel 6a
 - OS: Android 13
 - Browser Chrome 114.0.5735.131

**Comment by vanruesc** [comment]
The error implies that the `DepthDownsamplingMaterial` doesn't explicitly define a precision for float arrays. That's strange though, because default precision declarations are usually injected automatically by `three`. Maybe this has to do with how the arrays are initialized. Does your device support WebGL 2 or does it fall back to WebGL 1?

**Comment by marwie** [comment]
Yes the Pixel 6a supports webgl 2

**Comment by vanruesc** [comment]
This is likely a driver/browser/angle bug because the precision declarations are definitely at the top of the shader.

I've added explicit precision qualifiers to float array declarations in `postprocessing@6.32.2`. Could you please check if this fixes the issue?

**Comment by marwie** [comment]
Hi, I just rebased on 6.32.2 and ran `npm start` but the issue still persists on my phone

**Comment by vanruesc** [comment]
I've changed the array initializations in `postprocessing@6.33.3`. It would be great if you could test again with this update.

**Comment by marwie** [comment]
Hi @vanruesc I just updated to 6.33.3 and it works there - thank you for the fix

**Comment by vanruesc** [comment]
Nice, thanks for checking :+1:
