### ISSUE TITLE
'Resizer' only refers to a type, but is being used as a value here.ts(2693)

### ISSUE THREAD

**Issue by amir-khoshbakht** [pmndrs/postprocessing#510]
### Description of the bug

it seems there is a problem with Resizer function

### To Reproduce

create an empty react project using this command:
```yarn create react-app --template typescript```

and then import the "Resizer" function

### Expected behavior

it should work

### Screenshots

![image](https://github.com/pmndrs/postprocessing/assets/68753961/d30eec4d-8479-40d7-8bef-4ac2262157ce)

### Library versions used

    "@react-three/postprocessing": "^2.14.12",
    "three": "^0.153.0",

### Desktop

 - OS: window 10

**Comment by vanruesc** [comment]
`Resizer` was renamed to `Resolution` a long time ago. `Resizer` shouldn't be used anymore.
