### ISSUE TITLE
PatternTexture is working incorrectly in the outline effect demo.

### ISSUE THREAD

**Issue by hopoduck** [pmndrs/postprocessing#511]
### Description of the bug

When rendering for the first time without selecting anything, the pattern texture is applied to all screens.
The same applies to resizing the screen and rendering it again.

### To Reproduce

enable "use pattern" and resize screen

### Expected behavior

Pattern textures not visible

### Screenshots

![image](https://github.com/pmndrs/postprocessing/assets/64189819/1514717a-fcb6-411a-9b08-c9efd90558bc)

**Comment by vanruesc** [comment]
Thanks for the report. Looks like the masking logic needs a makeover.

**Comment by vanruesc** [comment]
Should be fixed in `postprocessing@6.33.0`.
