### ISSUE TITLE
 Adding 2 outlinepass to scene

### ISSUE THREAD

**Issue by whitecad** [pmndrs/postprocessing#515]
I want to add 2 outline pass to scene, first for hovered object second for selected objects.
Although the selection sets of both objects are different, the first one also paints the objects belonging to the second
selected image
<img width="619" alt="image" src="https://github.com/pmndrs/postprocessing/assets/128173321/8ea9478c-d7a5-4a76-98ba-446a1f6828cc">
selected and hover image (only wall hovered)
<img width="619" alt="image" src="https://github.com/pmndrs/postprocessing/assets/128173321/dae8c7c0-beed-4447-99eb-340348d50348">

**Comment by vanruesc** [comment]
https://github.com/pmndrs/postprocessing/issues/464#issuecomment-1475017106

**Comment by vanruesc** [comment]
Closing this as it seems to be resolved.
