### ISSUE TITLE
Chromatic Aberration and Depth of Field don't work together

### ISSUE THREAD

**Issue by MajorMeerkatThe3rd** [pmndrs/postprocessing#516]
### Description of the bug

When using the chromatic aberration effect and the depth of field effect at the same time the chromatic aberration is not visible anymore. This is independent to the effect order

### To Reproduce

Here is an example, if you remove the depth of field effect from the effect pass the chromatic aberration is visible again: https://codesandbox.io/s/xgtp9m

### Library versions used

 - Three: 0.152.2
 - Post Processing: 6.31.0

### Desktop

 - OS: Windows
 - Browser: Brave 1.52.130
 - Graphics hardware: NVIDIA Quadro T2000

**Comment by vanruesc** [comment]
For this use case, you'd need to break the effects up into separate `EffectPass` instances; one for DoF and one for CA. CA should probably be applied last.
