### ISSUE TITLE
Does EffectComposer inputBuffer autoClear?

### ISSUE THREAD

**Issue by dongho-shin** [pmndrs/postprocessing#521]
Hi guys I have a question
I want to readRenderTargetPixels of `EffectComposer.inputBuffer`
 because of capture `EffectComposer.render` result.

I check EffectComposer.inputBuffer used by result of rendering if `Pass.needSwap = true`
so I tried `WebGLRenderer.readRenderTargetPixels(effectComposer.inputBuffer, 0, 0, width, height, pixelBuffer)`
`pixelBuffer : Uint8ClampedArray(width * height * 4)` but still all values of pixelBuffer has zero

then is it timing issue or I miss that something clear the buffer?
Thanks in advance

**Comment by vanruesc** [comment]
`EfectComposer.inputBuffer` is private and shouldn't be accessed directly.

You could create a small [custom Pass](https://github.com/pmndrs/postprocessing/wiki/Custom-Passes) instead that performs the pixel read in the `render` method. Note that `needsSwap` should be set to `false` if the pass doesn't render anything to the output buffer.

**Comment by dongho-shin** [comment]
@vanruesc Thanks! i didnt think about that i will try
