### ISSUE TITLE
show darked testures with latest ver.

### ISSUE THREAD

**Issue by jomin398** [pmndrs/postprocessing#523]
### Description of the bug
show darked testures with latest ver, no throwed errors.

### To Reproduce

```
import { MMDLoader } from 'https://cdn.jsdelivr.net/npm/three@latest/examples/jsm/loaders/MMDLoader.js';
import { MMDAnimationHelper } from 'https://cdn.jsdelivr.net/npm/three@latest/examples/jsm/animation/MMDAnimationHelper.js';
import { OrbitControls } from 'https://cdn.jsdelivr.net/npm/three@latest/examples/jsm/controls/OrbitControls.js';
import { EffectComposer, EffectPass, RenderPass } from 'https://cdn.jsdelivr.net/npm/postprocessing@latest/+esm';
```

### Expected behavior

Expected as 1st image as no darked texture. (darked testures shown as 2nd image.)

### Screenshots

![with three 0 150 0ver](https://github.com/pmndrs/postprocessing/assets/23178638/7594b705-3f50-4b15-9c6e-d0897bd89be6)  

![with three latest ver](https://github.com/pmndrs/postprocessing/assets/23178638/899fa041-6c91-4ee4-a536-44cab4b811e5)

### Library versions used

 - Three: 0.155.0 (latest)
 - Post Processing: 6.33.0 (latest)

### Desktop

 - OS: Windows
 - Browser Chrome 115.0.5790.17
 - Graphics hardware: NVIDIA

**Comment by vanruesc** [comment]
This is probably related to the changes regarding `WebGLRenderer.useLegacyLights`.

See https://github.com/mrdoob/three.js/wiki/Migration-Guide#154--155 and https://discourse.threejs.org/t/updates-to-lighting-in-three-js-r155/53733 for details.

**Comment by jomin398** [comment]
i just crank up intensity null to 6 when i use `new THREE.DirectionalLight(0x7a7a7a);`
(change it as this `(0x7a7a7a,6)`)
now it fixed! thx

**Comment by vanruesc** [comment]
To make it look the same as before, you can convert your diffuse and light colors to sRGB with `new Color(oldColor).convertLinearToSRGB().toHexString()`. The intensity should be multiplied by `Math.PI` to match legacy mode.

**Comment by jomin398** [comment]
sorry to reopen... thx for help...

`three.module.js:9180 THREE.Color: Unknown color c1b6aa`
<html>
<body>


  setColorName | @ | three.module.js:9180
 -- | -- | --
   setStyle | @ | three.module.js:9159
   set | @ | three.module.js:8963
   Br | @ | three.module.js:8941
   pd | @ | three.module.js:42660
   Ad | @ | three.module.js:43141


</body>
</html>
gatting it from console.warn. by just excute code as below.

```
const color = new THREE.Color(0x887766).convertLinearToSRGB().getHexString();
const directionalLight = new THREE.DirectionalLight(color, Math.PI * 0.35);
```

**Comment by CodyJasonBennett** [comment]
Remove the `.getHexString()` part, DirectionalLight expects a color instance https://threejs.org/docs/#api/en/lights/DirectionalLight. Please use three's forum for usage questions.
