### ISSUE TITLE
getContextAttributes error with WebGPU

### ISSUE THREAD

**Issue by jomin398** [pmndrs/postprocessing#524]
### Description of the bug

`Uncaught TypeError: Cannot read properties of undefined (reading 'getContextAttributes')
    at bt.setRenderer (index.js:7114:30)
    at new bt (index.js:7051:10)
    at effectBinder`
just not yet support `WebGPU`?

i tried to digging to find...
```
console.log(renderer.domElement.getContext('2d').getContextAttributes().alpha)
//it returns true
```

### To Reproduce
```js
//effectBinder
renderer = new WebGPURenderer();
FinalComp = new EffectComposer(renderer);
```
### Library versions used

 - Three: latest (r155)
 - Post Processing: latest (v6.33.0)

### Desktop

 - OS: Windows
 - Browser Chrome

### Mobile
 - OS: Android
 - Browser: Chrome

**Comment by CodyJasonBennett** [comment]
This and most three.js libraries don't support WebGPU. Furthermore, it does not implement the API the WebGLRenderer does, so they're incompatible in shape to begin with. Work here is blocked behind three's upcoming nodes-materials and universal renderer which are WIP and undocumented ATM.
