### ISSUE TITLE
Screen glitch with Bloom on M1 Mac

### ISSUE THREAD

**Issue by jjv360** [pmndrs/postprocessing#526]
### Description of the bug

When using the `BloomEffect` on an M1 Mac (Chrome and Edge), there is a glitch that causes the screen to go black in certain areas. This only seems to happen with certain models though...

On Windows, the same models and code do not have any issue.

### To Reproduce

Here is a JSFiddle showing the issue: https://jsfiddle.net/KevTheDev/3k1nyhz2/

### Expected behavior

No glitches should be visible.

### Screenshots

https://github.com/pmndrs/postprocessing/assets/2771104/07cb5f7c-a249-4958-9ab1-3a91b6ec75fe

### Library versions used

 - Three: 0.155.0
 - Post Processing: 6.33.0

### Desktop

 - OS: macOS Ventura - 13.4.1 (c) (22F770820d)
 - Browser: 
   - Edge 115.0.1901.203 (Official build) (arm64)
   - Chrome 116.0.5845.96 (Official Build) (arm64)
 - Graphics hardware: Mac M1

**Comment by vanruesc** [comment]
Thanks for the report, I'm able to reproduce the issue on a linux mashine with integrated Intel graphics.

This seems to be caused by invalid color values that result in undefined hardware behaviour. I'll look into it.

**Comment by vanruesc** [comment]
This issue is caused by a misconfiguration in the box model. The model uses an incorrect texture as a normal map. See https://github.com/mrdoob/three.js/issues/26767 for details.
