### ISSUE TITLE
Different visual effect between outline enable/disable in three r155

### ISSUE THREAD

**Issue by FindDefinition** [pmndrs/postprocessing#527]
### Description of the bug

The scene get different result if I disable/enable outline effect in three r155. no problem in r154.

### To Reproduce

[codesandbox](https://codesandbox.io/s/outline-not-showing-for-2-9-0-and-above-forked-cq4343?file=/src/App.js:1026-1040)
comment the `EffectComposer` to see the difference.

### Expected behavior

scene should be same between effectcomposer enable/disable.

### Screenshots

disable effectcomposer:
![image](https://github.com/pmndrs/postprocessing/assets/73811981/c0c841f2-04cc-4aac-bcc0-b73738fe3415)
enable effectcomposer:
![image](https://github.com/pmndrs/postprocessing/assets/73811981/19493e48-783c-46a3-bace-2cae0d6a22d9)

### Library versions used

 - Three: r155
 - Post Processing: 6.33.0
 - React Post Processing: 2.15.1

### Desktop

 - OS: Ubuntu
 - Browser chrome/firefox
 - Graphics hardware: NVIDIA GTX 1080

**Comment by FindDefinition** [comment]
@vanruesc I can't understand, why is this behavior expected? Do I need to use two different light parameter sets with `EffectComposer` enabled/disabled?

**Comment by vanruesc** [comment]
This issue is unrelated to `postprocessing`.

You can set `gl.useLegacyLights = true` to get the old lighting behaviour back, but you should adjust your scene according to the information from the migration guide.
