### ISSUE TITLE
Outline effect per object?

### ISSUE THREAD

**Issue by sdraper69** [pmndrs/postprocessing#532]
I was planning on using the outline effect for selection, as in general, it looks great, however, there is a major flaw when using it for selection in that when you have multiple objects selected, with some in front of the others, you can't tell what is selected and what isn't. E.g on the official demo

![image](https://github.com/pmndrs/postprocessing/assets/25779335/0f731e7b-82b5-4ec0-998e-c6811ea3eb33)

You can't tell if the red disc is selected in this orientation - in fact it looks like it's not.

How are other people using this for selection purposes if you have a reasonably complex scene, this could occur a lot?

My ideal feature request would be to have a per-object outline.

**Comment by vanruesc** [comment]
This is currently the intended behaviour. See also https://github.com/pmndrs/postprocessing/issues/530#issuecomment-1714643198.
