### ISSUE TITLE
Regression: DepthOfFieldEffect doesn't honor alpha channel anymore in r 6.33.0

### ISSUE THREAD

**Issue by lviggiani** [pmndrs/postprocessing#533]
I have upgraded my project to `postprocessing.js` `6.33.0` and `three` `156` (**nothing else has changed in my code**) and by adding `DepthOfFieldEffect` to my effects pass, I get a black background on final image rather than transparent.

Here are my settings:

```typescript
export const RENDERER = {
    powerPreference: "high-performance",
    antialias: false,
    alpha: true,
    stecil: false,
    depth: false
}

export const COMPOSER = {
    frameBufferType: THREE.HalfFloatType,
    multisampling: 4
}

//DepthOfFieldEffect 
export const DOF = {
    focusDistance: 0.00015,
    focalLength: 0.0005,
    bokehScale: 10,
    height: 1000
}
```

My renderer has clearColor set to transparent `renderer.setClearColor(0x000000, 0);`

As told, by downgrading to r `6.32.2` everything works as expected.
I'm using npm prebuilt package; I haven't tried from latest git source.

**Comment by vanruesc** [comment]
Duplcate of #529. A fix is on the way.
