### ISSUE TITLE
Requesting SSR be added to this library.

### ISSUE THREAD

**Issue by kitaedesigns** [pmndrs/postprocessing#534]
### Is your feature request related to a problem?

SSR already exists in the vanilla threejs Post Processing library but would be great to have in Pmdnrs so that users don't have to add it manually and load two PP libraries or just that one shader. 

### Describe the solution you'd like

Adding SSR to the current library would simplify adding reflections and also up the visual quality for everyone. 

### Describe alternatives you've considered

Tried adding it manually in my own projects and it is just tedious and inefficient to use two Post Processing libraries.

**Comment by vanruesc** [comment]
SSR is already on the roadmap (#279). It will be added once v7 is done.
