### ISSUE TITLE
BloomEffect is distorted when resizing the window

### ISSUE THREAD

**Issue by tjvezina** [pmndrs/postprocessing#536]
### Description of the bug

When resizing the window, the bloom effect is distorted, i.e. the bloom radius does not stay consistent, but is instead stretched along with the window.

### To Reproduce

- Have a `BloomEffect` active
- Resize the window (for example, start with a very small window, refresh the page/sandbox to reset the bloom effect, then stretch the window large to see the issue most clearly)

*See [sandbox project](https://codesandbox.io/s/bloom-effect-resize-issue-yz5fnn) for demo*

### Expected behavior

Bloom effect is consistent, regardless of window resizing.

### Screenshots

Normal (left) / After resizing (right)
![image](https://github.com/pmndrs/postprocessing/assets/1713664/c9d7c35f-b554-469c-8e50-d2b52ef45323)&nbsp;![image](https://github.com/pmndrs/postprocessing/assets/1713664/a6660aa3-747c-412a-8b22-cadcbe5c46c6)

### Library versions used

 - Three: 0.156.0
 - Post Processing: 6.33.1

### Desktop

 - OS: Windows
 - Browser: Brave v1.58.135
 - Graphics hardware: NVIDIA

**Comment by vanruesc** [comment]
This is actually caused by `LineMaterial`. The line thickness doesn't scale with the canvas size. You can verify this by removing the `bloomEffect` from the `EffectPass`.

I think you may have to update the `resolution` uniform of the `LineMaterial` on resize. That's just a guess though.

**Comment by tjvezina** [comment]
Ah you're right, I feel silly for missing that! Adding `lineMaterial.resolution = new Vector(window.innerWidth, window.innerHeight);` to the resize function fixed the problem, thanks!
