### ISSUE TITLE
orthographicDepthToViewZ is wrong

### ISSUE THREAD

**Issue by butzemannbiber** [pmndrs/postprocessing#541]
I think there is a problem with the reciprocal method of "viewZToOrthographicDepth"

### To Reproduce

orthographicDepthToViewZ(viewZToOrthographicDepth(0.01, 0.1, 100),0.1, 100) != 0.01

### Expected behavior

viewZToOrthographicDepth(orthographicDepthToViewZ(0.01, 0.1, 100),0.1, 100) == 0.01

**Comment by vanruesc** [comment]
The math for these functions was copied from [here](https://github.com/mrdoob/three.js/blob/0de4e75ee65c3238957318b88ef91b6597e23c1e/src/renderers/shaders/ShaderChunk/packing.glsl.js#L39-L44) and should be correct.

The function `orthographicDepthToViewZ` returns negative values and `viewZToOrthographicDepth` expects negative values for viewZ. The roundtrip works if you avoid rounding errors:

```js
const near = 1;
const far = 999;
viewZToOrthographicDepth(orthographicDepthToViewZ(0.01, near, far), near, far) === 0.01
```
