### ISSUE TITLE
Three package Denial of Service issue

### ISSUE THREAD

**Issue by Haydeng1** [pmndrs/postprocessing#542]
### Description of the bug

Postprocessing uses the package three version that is not up to date and has a Denial Of Service regex issue.
Can this be updated?
The Latest three 0.158.0 version has a fix of the issue I believe.

**Comment by vanruesc** [comment]
Postprocessing currently supports `three` r138 - r157. This range will be extended to include r158 soon. I'm not aware of any DoS issues that are present in these versions. The last DoS issue was in versions prior to r125.

**Comment by vanruesc** [comment]
Updated the peer dependency range to include r158 in `postprocessing@6.33.3`.
