### ISSUE TITLE
OverrideMaterialManager functions should be public

### ISSUE THREAD

**Issue by schwyzl** [pmndrs/postprocessing#546]
### Description of the bug

Hi, I need to use the OverrideMaterialManager in my own version of RenderPass but I can't access the private render function from OverrideMaterialManager. Is there a specific reason why this is private? If not can it be made public?

### Library versions used

 - Three: [e.g. latest]
 - Post Processing: [e.g. 6.33.3]

**Comment by schwyzl** [comment]
I can see that things are changing quite dramatically in v7 so I'll explain a bit my use case and perhaps you can guide me on how to use this lib to aid that.

Short version is I want a pass with two render calls, one with a material override, and one without.

Long version is; I am trying to render a volume with the ray beginning on a clipping plane. I have tried doing this with the [volume shader from the three examples](https://threejs.org/examples/webgl2_materials_texture3d.html), but haven't managed to convert the clipping plane to the approriate 3D texture UVW coordinate space to work properly. I found [this example](http://www.lebarba.com/Index.html) that does things differently... Render two passes to first get the world space coordinate of the back faces, then the front. I'm unclear whether it will solve anything for me but will give it a go. Since I am using this postprocessing lib I thought I would extend Pass to add a MaterialOverrideManager, then in the render call do each render one after another, one with the override, one without.

```
        // render world space coordinates of the back face texture
        renderer.setRenderTarget(inputBuffer);
        renderer.setClearColor(0x000000, 0.0);
        renderer.clear(true, true, true);
        this.overrideMaterialManager.render(renderer, this.volumeContainer, this.getViewerCamera());
        
        // render output
        renderer.setRenderTarget(outputBuffer);
        this.material.uniforms['u_backFaceCoords'].value.copy(inputBuffer.texture),
        renderer.render(this.volumeContainer, this.getViewerCamera());

```

**Comment by vanruesc** [comment]
> Is there a specific reason why this is private?

That's unintentional - thanks for pointing it out.

> I want a pass with two render calls, one with a material override, and one without.

Considering that the `OverrideMaterialManager` is only a workaround that fixes certain edge cases in v6, I'd recommend using three's override system directly via [Scene.overrideMaterial](https://threejs.org/docs/#api/en/scenes/Scene.overrideMaterial). With this approach you can use two `RenderPasses` to render two scenes of which one would use an override material.

Any issues related exclusively to override materials should be reported in three's issue tracker.

**Comment by schwyzl** [comment]
Cheers :)
