### ISSUE TITLE
[Question]: Custom Composer/RenderPass resolution/size different from "main" renderer 

### ISSUE THREAD

**Issue by dghez** [pmndrs/postprocessing#549]
Hey there!
I'm doing an off-screen postprocessing pipeline and use the final pass (aka the result from a CopyPass) as texture on a mesh, essentially like
```
    composer.addPass(renderPass)
    composer.addPass(shaderPass)
    composer.addPass(copyPass)
    .....
    
    mesh.material.diffuse = copyPass.texture
```

Is there a way to change the size/resolution of the `RenderPass`' render-target without affecting the main resolution of the renderer?

For example I have the main context dpr = 2 (and I have to keep at 2) but I don't want to have the Composer's dpr = 2, 
just 1 or whatever different from the main dpr, so I can save some performances, but I can't see any method to do that, even `renderPass.setSize(...)` doesn't do the trick. (worth a shot)

The solution I'm thinking about can be create a render-target manually, render what I need and then skip the render pass going straight to the second pass (shader pass in my case) and pass manually as uniform the render target I created

```
const rt = new WebglRenderTarget(....)
const shaderPass = new ShaderPass(.....) <<< custom uniform rt.texture 
...
composer.addPass(shaderPass)
composer.addPass(copyPass)

...
animate(){
  gl.setRenderTarget(rt)
  gl.render(scene, camera)
  gl.setRenderTarget(null)
  
  composer.render()
}

```

Any thought on this?
Thanks in advance ❤️

--
EDIT: Maybe as enhancement we can expose `RenderPass.getRenderTarget()` so we can modify based on our needs?

**Comment by vanruesc** [comment]
Hi,

unfortunately, this use case is currently not supported. `RenderPass.setSize` doesn't do anything since this pass renders to the main frame buffers that are managed by the composer.

I don't plan on adding more features to v6. The next major version will provide persistent resolution settings for each `Pass` and there will be an alpha release soon.

**Comment by dghez** [comment]
Hey @vanruesc , at the end I've solved exactly the way I suggested :)
