### ISSUE TITLE
Gltf Emissive Strength not being factored into Bloom

### ISSUE THREAD

**Issue by kitaedesigns** [pmndrs/postprocessing#551]
It seems that the gltf extension, KHR_EmissiveStrength for Emissive values over 1 is not correctly be applied to the Bloom Pass. If Bloom Threshold is set to 1 it is expected that the the Emissive Materials with values over 1 should still produce Bloom.

Adding an example or code that takes the float targets from Emissive Strength into the EffectComposer Constructor to correctly apply Bloom to anything brighter than [0,1] would be very helpful.

**Comment by vanruesc** [comment]
Please make sure that high precision frame buffer are enabled:

```js
import { HalfFloatType } from "three";

const composer = new EffectComposer(renderer, {
	frameBufferType: HalfFloatType
});
```

**Comment by vanruesc** [comment]
Closing this as it seems to be resolved.
