### ISSUE TITLE
Would it be possible to add AgX to the Tonemapping options?

### ISSUE THREAD

**Issue by kitaedesigns** [pmndrs/postprocessing#555]
Now that Blender 4.0 has switched to AGX being the default Tonemapping mode, does it make sense to add to add here as well so that assets look as similar as possible?

See more about AgX here.
https://github.com/EaryChow/AgX

**Comment by vanruesc** [comment]
Yes, support for AgX would be good, but I think we should wait until it's implemented in `three`. Then it should be possible to tap into that logic instead of implementing it twice.

Related dicussion: https://github.com/mrdoob/three.js/issues/26479#issuecomment-1693335825

**Comment by VanderSP** [comment]
I started using it today! and I also plan to use this POSTFX MIXER!!!!!!!!

**Comment by vanruesc** [comment]
Added `ToneMappingMode.AGX` in `postprocessing@6.34.0`.

**Comment by kitaedesigns** [comment]
Hey @vanruesc thank you for adding AgX! This was a great addition. I'm testing using a baked lighting model between Blender AgX and threejs's and pmndr's AgX using the same HDR to light the scene at an intensity of 1, and no lights in the scene but still noticing some differences in color, namely the threejs version seems to be more washed out. Is this just a difference of how AgX is implemented in WebGL vs OpenGL? 

![image](https://github.com/pmndrs/postprocessing/assets/23407511/1d254d7b-5af7-423f-ab7c-9b37c876222b)

**Comment by VanderSP** [comment]
Hey, AGX is not just agx... theres punchy, golden, idk many presets of something... threejs implemented agx but still thinking about the presets... maybe this is the issue, i think it deals with some kind of contrast... still so new... i leave my blender in PUNCHY lol

**Comment by vanruesc** [comment]
@kitaedesigns Please try comparing results with vanilla `three` first. Three's physically-based lighting model is not exactly the same as the one Blender uses so some differences are to be expected.

@VanderSP I think it's safe to assume that @kitaedesigns used the default AgX preset in Blender. Results would obviously differ if that wasn't the case.

**Comment by kitaedesigns** [comment]
Hi @vanruesc, yes here is a comparison with threejs and blender's AgX. Blender on the Left. Threejs on the Right. Using the exact same asset and cubemap.

Blender AgX with Exposure at 0 vs Threejs AgX with Exposure at 1.
![image](https://github.com/pmndrs/postprocessing/assets/23407511/199808aa-b6d2-498c-a22b-ece5de237e44)

![image](https://github.com/pmndrs/postprocessing/assets/23407511/da8da021-f7d2-4897-b13e-4443afac5d12)


If I manually adjust each one's exposure I can get them quite close but I think the expectation would be that Exposure of 1 with AgX tonemapping in Threejs should be the same as Exposure 0 AgX tonemapping in Blender.


![image](https://github.com/pmndrs/postprocessing/assets/23407511/0a1ee81f-c9c4-4508-b7a4-2f8d34f30440)

**Comment by vanruesc** [comment]
Thanks, I think three's output looks more pale in comparison, but it's hard to tell with this model and a blurred background. A comparison of your original scene from this [comment](https://github.com/pmndrs/postprocessing/issues/555#issuecomment-1879353043) would be useful.

My current guess is that the visual differences between Blender and `three` are not caused by `postprocessing` and are therefore out the scope for this project. In that case, it might be worth a shot to create a forum post over at [three](https://discourse.threejs.org/) to discuss this as a potential issue.

**Comment by kitaedesigns** [comment]
Ok I will crosspost in the AgX thread here https://github.com/mrdoob/three.js/issues/27362

Here are the assets.

GLB
https://1drv.ms/u/s!AksR0p9ftT9Yjilvft0H-B_IUNun?e=ttLJdA

HDR (this is the blender default)
https://1drv.ms/u/s!AksR0p9ftT9Yjiy5yFGQuDXIsuKo?e=wBMQgz

**Comment by VanderSP** [comment]
Ah now i see... when comparing to threejs, we are on NONE/BASE... how do you are keeping it more constrasty? epxosure value? or envmapIntensity?
