### ISSUE TITLE
Missing edgeThinkess parameter

### ISSUE THREAD

**Issue by rubeniskov** [pmndrs/postprocessing#566]
### Is your feature request related to a problem?

I'm not sure about this was disscused before (I was searching in the closed issues), but I tried to adjust the `edgeThinkess` of the `OutlineEffect` but its seem to be missing 

The example from threejs manage besides the `egeStrength` a `edgeTickness` parameter to have more control about the side of the ouline. 

<img width="1392" alt="image" src="https://github.com/pmndrs/postprocessing/assets/6261914/930ba659-6391-40e0-b0bc-c8f6dce3df3f">

[https://threejs.org/examples/webgl_postprocessing_outline.html](https://threejs.org/examples/webgl_postprocessing_outline.html)

### Describe the solution you'd like

I would like to propose the addition of an `edgeThickness` parameter to the `OutlineEffect` in order to control the thickness of the edges in the outlined objects. 

### Describe alternatives you've considered

Currently, I'm not able to adjust the thickness of the edges when using the `OutlineEffect`. 

I will try to investigate how to contribute for this using the threejs example as reference if someone is interesting on this feature.

**Comment by rubeniskov** [comment]
@AlejandroOrtega1

**Comment by vanruesc** [comment]
The `edgeThickness` parameter of the `OutlinePass` in `three` is an alias for the [blur kernel radius](https://github.com/mrdoob/three.js/blob/ff4f0adcd336f90e5a61d37ba1a3df13d54a197c/examples/jsm/postprocessing/OutlinePass.js#L375).

In `postprocessing` the thickness can be controlled via [OutlineEffect.blurPass.blurMaterial.scale](https://pmndrs.github.io/postprocessing/public/docs/class/src/materials/KawaseBlurMaterial.js~KawaseBlurMaterial.html#instance-set-scale). Please note that larger scales lead to artifacting if the main kernel size is too small. The kernel size can be adjusted via [OutlineEffect.blurPass.blurMaterial.kernelSize](https://pmndrs.github.io/postprocessing/public/docs/class/src/materials/KawaseBlurMaterial.js~KawaseBlurMaterial.html#instance-member-kernelSize) which accepts values of type [KernelSize](https://pmndrs.github.io/postprocessing/public/docs/variable/index.html#static-variable-KernelSize).

**Comment by rubeniskov** [comment]
Thanks for the clarification
