### ISSUE TITLE
Minor documentation update needed

### ISSUE THREAD

**Issue by thibka** [pmndrs/postprocessing#567]
Hi,

It doesn't seem like we can contribute to the documentation other than here, so here I go:

I've noticed that the OPTIMIZED_CINEON and UNCHARTED2 tonemapping modes are swapped in this table:
https://pmndrs.github.io/postprocessing/public/docs/variable/index.html#static-variable-ToneMappingMode

The value of OPTIMIZED_CINEON is 4 but it's listed on the 4th row (instead of the 5th)
and the value of UNCHARTED2 is 3 but it's listed on the 5th row (instead of the 4th)

That's it!

Cheers

**Comment by vanruesc** [comment]
> It doesn't seem like we can contribute to the documentation

The docs are generated from the [doc comments in the code](https://github.com/pmndrs/postprocessing/blob/6ce1e7dfd73c8101295baa1ad5ef653fd28195df/src/enums/ToneMappingMode.js#L1-L12).

I've adjusted the docs in `postprocessing@6.34.2` although the order of the enum values doesn't really matter. The numeric values of the constants are an internal implementation detail after all.
