### ISSUE TITLE
OutlineEffect: outline is missing on parts of object.

### ISSUE THREAD

**Issue by trusktr** [pmndrs/postprocessing#572]
### Is your feature request related to a problem?

Screenshot:

<img width="1355" alt="Screenshot 2024-02-12 at 2 40 05 PM" src="https://github.com/pmndrs/postprocessing/assets/297678/773c20b6-b127-45cf-b9af-a6d1cf6140c4">

### Describe the solution you'd like

We need an option to not combine outlines of multiple objects into one.

Three's `OutlineEffect` works as desired:

https://threejs.org/examples/?q=toon#webgl_materials_toon

<img width="1247" alt="Screenshot 2024-02-12 at 2 43 06 PM" src="https://github.com/pmndrs/postprocessing/assets/297678/c143bb42-86b9-4665-8f43-feb4ff588971">

### Additional context

Can we use both Three's `EffectComposer` and `postprocessing`'s `EffectComposer` at the same time? If so, then we can use `OutlineEffect` from Three's examples and use the rest from postprocessing.

**Comment by vanruesc** [comment]
Hi, three's [OutlineEffect](https://github.com/mrdoob/three.js/blob/master/examples/jsm/effects/OutlineEffect.js) can be used together with `postprocessing` since it's not actually a fullscreen pass.

**Comment by jo-chemla** [comment]
Hi there! Is there a general rule of thumb for which threejs `original postprocessing` effects do work with `your EffectComposer implementation`? 

I've tried to use the original OutlineEffect with your EffectComposer with no luck. The following code block sums-up the main points, but this lead to a silent fail - no errors printed in console, but canvas just stays with the DOM color and is not even cleared with the renderer clear color. Is this the way to import the original OutlineEffect? 

```js
import { EffectComposer, EffectPass, RenderPass, BlendFunction } from 'postprocessing';
import { OutlineEffect } from 'three/examples/jsm/effects/OutlineEffect';

composer = new EffectComposer( renderer, { frameBufferType: HalfFloatType, stencilBuffer: true } );
composer.addPass( new RenderPass( scene, camera ));

// OutlineEffect works when outlineEffect.selection.add( c );
outlineEffect = new OutlineEffect( scene, camera, { edgeStrength: 3.0, visibleEdgeColor: 0x53fbff, hiddenEdgeColor: 0x53fbff, blur: true, xRay: false, blendFunction: BlendFunction.SCREEN } ); // SRC SCREEN
const outlinePass = new EffectPass( camera, outlineEffect );
composer.addPass( outlinePass );

// The below function is hooked to onModelLoad
scene.traverse( ( c ) => {
	if ( c.isMesh ) 
		if ( outlineEffect?.selection )
			outlineEffect.selection.add( c );
})
```

**Comment by vanruesc** [comment]
Despite its name, [OutlineEffect](https://github.com/mrdoob/three.js/blob/master/examples/jsm/effects/OutlineEffect.js) is not an [Effect](https://github.com/pmndrs/postprocessing/blob/e053ac37ed095fafa31d3bb377e37ffa7810f12b/src/effects/Effect.js). I can see how this can be confusing, but it's a completely different thing.

Passes from `three` are incompatible with `postprocessing` due to API differences.

**Comment by jo-chemla** [comment]
Ok thanks for getting back so fast as always. I think I was mislead by your previous comment which should probably be `three's OutlineEffect can't be used [...]`

**Comment by vanruesc** [comment]
No, that comment was correct. Here's how you'd use `OutlineEffect` from `three`:

```js
const outlineEffect = new OutlineEffect(renderer);
let renderingOutline = false;

scene.onAfterRender = function() {

	if(renderingOutline) {

		return;

	}

	renderingOutline = true;

	outlineEffect.renderOutline(scene, camera);

	renderingOutline = false;

};
```

Note: that's the `scene`, you'd render using a `RenderPass` via `postprocessing`. Further passes have nothing to do with `outlineEffect`.

**Comment by vanruesc** [comment]
Closing this as it seems to be resolved.
