### ISSUE TITLE
Implement DualKawaseBlurPass

### ISSUE THREAD

**Issue by vanruesc** [pmndrs/postprocessing#580]
### Description

Implement a `DualKawaseBlurPass`.

References:
- https://www.froyok.fr/blog/2021-09-ue4-custom-lens-flare/ (see section about Dual Kawase)
- https://www.shadertoy.com/view/3td3W8
- https://phabricator.kde.org/D9848

### Tasks

- [ ] Create down- and upsampling shader materials.
- [ ] Create `DualKawaseBlurPass`.
- [ ] Add unit test.

**Comment by balraj-johal** [comment]
Hi @vanruesc, could I be assigned this issue? I'm already halfway through an implementation, I've got the down & upsampling working, and now just need to port over the Kawase shaders :)

**Comment by vanruesc** [comment]
Nice, thanks for picking this up!

**Comment by vanruesc** [comment]
Superceded by `MipmapBlurPass`.
