### ISSUE TITLE
Implement ColorDepthEffect

### ISSUE THREAD

**Issue by vanruesc** [pmndrs/postprocessing#589]
### Description

Implement a `ColorDepthEffect`.

### Tasks

- [x] Create `ColorDepthEffect`.
- [x] Create `color-depth` demo.
- [x] Add unit test.

### Implementation Details

- The implementation from v6 can be copied mostly as-is.

**Comment by benjamin-white** [comment]
Hello, I'd like to take a look at this one if that's ok please?

**Comment by vanruesc** [comment]
Sure, have fun 👍

**Comment by benjamin-white** [comment]
Great thanks @vanruesc

I have opened a PR here: https://github.com/pmndrs/postprocessing/pull/604 If it's generally the right shape let me know, if not, no worries :)
