### ISSUE TITLE
Implement ScanlineEffect

### ISSUE THREAD

**Issue by vanruesc** [pmndrs/postprocessing#595]
### Description

Implement a `ScanlineEffect`.

### Tasks

- [x] Create `ScanlineEffect`.
- [x] Create `scanline` demo.
- [x] Add unit test.

### Implementation Details

- The implementation from v6 can be copied mostly as-is.

**Comment by balraj-johal** [comment]
Hi, I'd like to help out with this ticket if possible. As the implementation can be mostly lifted from V6 this seems like something I can take on :) Also confirming that I have read the contributors guide.

**Comment by vanruesc** [comment]
Thanks! Feel free to ask if somethings unclear.
