### ISSUE TITLE
three.js incompatibilities in r162 due to code deprecated in r152

### ISSUE THREAD

**Issue by hybridherbst** [pmndrs/postprocessing#603]
### Description of the bug

three.js r162 will remove the legacy LinearEncoding and sRGBEncoding fields (they're already gone on dev). See https://github.com/mrdoob/three.js/pull/27656

This currently breaks the v6 postprocessing package. I think while v7 is in alpha it would be good to still support recent three.js versions if possible.

They have now been deprecated since r152 (https://discourse.threejs.org/t/updates-to-color-management-in-three-js-r152/50791), so I think it's been enough time to update here too. What do you think?

### To Reproduce

Use v6 version of the package with three dev branch (after the merge of [this PR](https://github.com/mrdoob/three.js/pull/27656)).

### Screenshots

<img width="961" alt="image" src="https://github.com/pmndrs/postprocessing/assets/2693840/734d8e57-9497-4dbd-948f-fbd0919eb573">

### Library versions used

 - Three: [r162dev]
 - Post Processing: [6.34.3]

**Comment by vanruesc** [comment]
Thanks for the heads-up!

> I think it's been enough time to update here to. What do you think?

Yeah, we'll have to raise the minimum version of `three` to r152 and remove the old code.

> I think while v7 is in alpha it would be good to still support recent three.js versions if possible.

v6 will be updated regularly at least until v7 is production-ready. For v7, I'm thinking about supporting the six most recent releases of `three`. Older versions may still work, but won't be officially supported. The first release of v7 will also most likely require the most recent version of `three` at that time, expanding forward until the range includes six releases.

Technically speaking, every peer dependency version update would be a breaking change that necessitates a major version bump, but almost every `three` release contains some kind of breaking change, so I'm not sure if we should follow semver that closely in that regard.

**Comment by hybridherbst** [comment]
I know, three versioning is fun...

> [for 6.x] raise the minimum version of three to r152 and remove the old code
> [for 7.x] will also most likely require the most recent version of three at that time

Both sound good! Thanks!

**Comment by vanruesc** [comment]
@dellwatson The required peer dependency version range for a specific release is specified on the [release page](https://github.com/pmndrs/postprocessing/releases).

> what's the reason to keep update the 6.x now?

Not sure what you mean by that.
