### ISSUE TITLE
Regression: Incorrect import `/node_modules/three/addons/misc/Timer.js`

### ISSUE THREAD

**Issue by hybridherbst** [pmndrs/postprocessing#611]
### Description of the bug

I think this is a regression introduced by https://github.com/pmndrs/postprocessing/commit/2aab3111cd56627b17d86f1869eac37ca66321e0. 
The timer import incorrectly uses "addons" which requires import maps support or correct package.json exports parsing (not available for every tool/bundler/combination, see https://github.com/mrdoob/three.js/pull/27381)

Example when using Vite 4.x:
![image](https://github.com/pmndrs/postprocessing/assets/2693840/e81709d9-5323-48c9-b8c9-0f6706a41b08)

I think it should use `three/examples/jsm` instead of `three/addons`.

**Comment by vanruesc** [comment]
Thanks for the report! That's a bummer. I'll prepare a fix in a bit.

**Comment by vanruesc** [comment]
Should be fixed in `postprocessing@6.35.1`.

**Comment by sommerper** [comment]
I installed via npm and it seems to still be in there:
![image](https://github.com/pmndrs/postprocessing/assets/1512048/df9c3671-b7ed-4830-a8dc-7ac49d5587e5)

**Comment by vanruesc** [comment]
@sommerper Uh oh, That's another regression. `Timer` was added in `three` r160 which means that using older versions of `three` results in an error. I'll push a fix tomorrow.

**Comment by vanruesc** [comment]
@sommerper Should be fixed in `postprocessing@6.35.2`.
