### ISSUE TITLE
When use EffectComposer, the GizmoViewport disappear

### ISSUE THREAD

**Issue by shunmian** [pmndrs/postprocessing#631]
### Description of the bug

When use `EffectComposer` for selection purpose, the `GizmoViewport` from @react-three/drei disappear

### To reproduce

see [code](https://codesandbox.io/p/sandbox/selective-outlines-forked-f84qdz?file=%2Fsrc%2FApp.js%3A27%2C18)

### Expected behavior

The GizmoViewport should be visible

### Library versions used

    "@react-three/drei": "9.32.0",
    "@react-three/fiber": "8.8.2",
    "@react-three/postprocessing": "2.6.2",
    "postprocessing": "6.28.7",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-scripts": "5.0.1",
    "three": "0.144.0"

**Comment by beginnerJq** [comment]
Set the `renderPriority={1}` props on GizmoHelper

**Comment by vanruesc** [comment]
Closing this since it's related to react and thus out of scope for this project.
