### ISSUE TITLE
question: is there a way to get renderer.info for the renderPass?

### ISSUE THREAD

**Issue by tom-twinlabs** [pmndrs/postprocessing#636]
when getting trying to gather stats about my scene I'm using renderer.info but it always shows triangles: 1. Of course this is expected since the effect are rendering a single triangle, but is there some sort of way to get the renderer.info from the initial pass?

thank you

**Comment by tom-twinlabs** [comment]
I was able to get this in the end with 

```
const {gl} = useThree();
gl.autoClear = false
gl.info.autoReset = false
useFrame((state) => {
	console.log(gl.info)
            
        state.gl.info.reset()
})	
```

perhaps it is something to do with react-three-fiber rather than this library... not sure. Either way I will close the issue

**Comment by vanruesc** [comment]
Postprocessing currently doesn't manage `renderer.info`. Resetting it manually like you described is a valid solution.

I'll add this to `GeometryPass` in v7 to make it the default behaviour.

**Comment by tom-twinlabs** [comment]
Thank you for your reply @vanruesc  . I wouldn't necessarily expect postprocessing to manage renderer.info. Having done a bit more digging into it, I don't thing three.js in-house effectcomposer does either.

thanks for the great library
