### ISSUE TITLE
draw call has big difference between invoking "composer.render()" in useframe and requestAnimationFrame

### ISSUE THREAD

**Issue by freddywhd** [pmndrs/postprocessing#637]
### Description of the bug

In my application,  I have used "View", the structure looks like below

```
<View index={1} className="view1" id="view1">
    a big scene
</View>
<View index={2} className="view2" id="view2">
   a small glb 
</View>
<View.Port />
```

the view 2 is not displayed in some rooms.   it is showed by some user interaction in a special room.

I added "postprocessing" such as bloom, AO, Vignette, SMAA for all room.  

I found the draw call has been increased a lot if I used option A to render the postprocessing effects.

option A:
useFrame((state, delta) => {
    composer.render(delta)
  }, 1)

Option B.
function renderScene(){
     animationReq = requestAnimationFrame(renderScene)
     composer.render()
}

then, I do a testing

test 1:   no postprocessing with 2 views.
<img width="408" alt="no processing with views" src="https://github.com/pmndrs/postprocessing/assets/22938569/24aa28ad-809b-4ef6-8117-5b65bc6b027b">

test2:  useframe with one view

<img width="305" alt="useframe with one view" src="https://github.com/pmndrs/postprocessing/assets/22938569/06810da6-0c98-4f4f-82ca-951b543969d3">

test3:  useframe with 2 views
<img width="277" alt="useframe with 2 views" src="https://github.com/pmndrs/postprocessing/assets/22938569/59506008-5306-40e1-8d41-6a53f577ce5c">

test4: requestAnimationFrame with views
<img width="295" alt="requestAnimationFrame with views" src="https://github.com/pmndrs/postprocessing/assets/22938569/0cb43ea6-2171-482c-a072-004b8af5ca91">

test5:  useframe with no views. 
<img width="306" alt="useframe with no views" src="https://github.com/pmndrs/postprocessing/assets/22938569/66b1ff7c-1255-4dd6-824b-4b393bbef225">

You can see if there is no views,  the draw call is similar no matter we use "useframe" or "requestAnimationFrame".   however, after we added "view",  the draw call, points, triangles have been increased a lot.

if I continuously use "requestAnimationFrame",  it will have trouble in 2nd view in the special room. the small glb in view2 didn't appear. it just display the same content in "view1".     however, if I use "useframe", then, no problem. just a huge draw call.   and if I remove postprocessing,  no problem in views as well. 

### To reproduce

Describe the steps to reproduce the behavior and provide a minimal example that demonstrates the issue. You can use the demo sandbox as a starting point: https://stackblitz.com/edit/postprocessing-v6

### Expected behavior

I think we should use useframe to keep same draw call as "requestAnimationFrame" in multiple views.

### Screenshots

refer to above. 

### Library versions used

 - Three: [e.g. X.XXX.X]
 - Post Processing: [e.g. X.X.X]
"@react-three/postprocessing": "2.16.2",
 "postprocessing": "^6.35.3",
"three": "0.163.0",

### Desktop

 - OS: [MacOs Sonoma 14.5]
 - Browser [e.g. Chrome 125.0.6422.61]
 - Graphics hardware: [e.g. NVIDIA]

**Comment by vanruesc** [comment]
SSAO is causing the drastic increase in draw calls because it has to render the given scene twice to write the normals to a texture. This issue will be fixed in v7 which uses MRT for this, but the new SSAO implementation isn't ready yet.

Bloom also adds `levels * 2` draw calls for the down- and upsampling steps. However, the performance impact of these draw calls should be small since there are only 2 material switches involved.

SMAA performs edge detection and weight calculation which adds 2 draw calls.

**Comment by freddywhd** [comment]
@vanruesc  thanks your explanation.  I understand that draw call will be increased.  however, it seems the issue caused by views.   is it possible that we force to render one view only?   and why requestAnimationFrame has no impact with views..

**Comment by vanruesc** [comment]
It's probably related to how `WebGLRenderer.info` is updated. By default, `postprocessing` doesn't manage it, so when it runs, the draw calls are reset for each pass and `EffectPass` by itself counts as one draw call which is probably why the rAF approach shows lower than expected draw call stats.

As for the views and `useFrame that's out of scope for this library since it's react code.

**Comment by vanruesc** [comment]
Closing this as it seems to be answered.

**Comment by freddywhd** [comment]
Last update,  I gave up this solution,  use MeshPortalMaterial + requestAnimationFrame to do the similar thing.
