### ISSUE TITLE
Question-Will this library move to be WebGPU based?

### ISSUE THREAD

**Issue by kitaedesigns** [pmndrs/postprocessing#643]
It seems like three.js is very quickly moving to webGPU and wondering if this library will also move to be webGPU based as well. Postprocessing can be pretty GPU intensive so I think it would make sense but curious to hear how the recent breakthroughs will affect the roadmap.

**Comment by vanruesc** [comment]
https://github.com/pmndrs/postprocessing/discussions/642#discussioncomment-10078208

> It seems like three.js is very quickly moving to webGPU

Postprocessing will move to WebGPU when the `WebGPURenderer` officially replaces the `WebGLRenderer`. The `WebGPURenderer` is functional but also still experimental/unfinished. There were [breaking changes](https://github.com/mrdoob/three.js/wiki/Migration-Guide#166--r167) regarding the WebGPU modules just recently in r167, so these components are still in flux.

> Postprocessing can be pretty GPU intensive so I think it would make sense

WebGPU will not automatically be faster at rendering. It offers features that can be used to optimize specific workloads, but those optimizations need to be implemented first.

> curious to hear how the recent breakthroughs will affect the roadmap

Which breakthroughs are you referring to specifically?

**Comment by kitaedesigns** [comment]
Gotcha, that all makes sense to me. 

Renaud has been doing some great work with all these new webGPU examples, some of them are PostProcessing based, many are not. https://threejs.org/examples/?q=webgpu%20postprocessing#webgpu_postprocessing

Also wondering how new breakthroughs in webGPU based real-time raytracing like in LGTracer https://lgltracer.com/editor/index.html will gel with Postprocessing.

**Comment by vanruesc** [comment]
> Also wondering how new breakthroughs in webGPU based real-time raytracing like in LGTracer https://lgltracer.com/editor/index.html will gel with Postprocessing.

That's a very broad question. New features are always nice. There will probably be new effects in the future that make use of them once they are more widely supported.

**Comment by vanruesc** [comment]
Closing this as it seems to be resolved.
