### ISSUE TITLE
Specular Aliasing

### ISSUE THREAD

**Issue by harrycollin** [pmndrs/postprocessing#649]
I'm encountering some issues with what I believe is called 'Specular Aliasing'. After many failed attempts to tweak SMAA & MSAA parameters I'm a bit stuck on how to solve this. The image attached showcases the issue quite well, the white edges on the front of the car appear even after using MSAA 8X with Ultra settings. 
![image](https://github.com/user-attachments/assets/df1250e6-b79f-4c8f-b3f0-f9adcb78ffed)

A similar problem has been talked about over [here](https://discourse.threejs.org/t/antialiasing-problem-thin-light-reflections-on-objects-edges-look-jagged/30713/11) but doesn't seem to have a concrete solution. I'm open to any suggestions :)

**Comment by vanruesc** [comment]
This doesn't look like it's related to `postprocessing`. Does the problem also occur without using `postprocessing`?

There is not enough information in the description of the issue. Reproduction steps have also not been provided and the issue template has been ignored.

Moving this to the discussions board.
