### ISSUE TITLE
Using 2 instances of SelectiveBloomEffect: second instance ignored, but its selection merges with the first

### ISSUE THREAD

**Issue by thibka** [pmndrs/postprocessing#653]
Hi, 

### Description of the bug

When using two instances of `SelectiveBloomEffect`, only the first instance is effectively applied on screen. The second one seems ignored. However, the `selection` from the second instance ends up being added to the first bloom effect.

### To reproduce

Here's a minimal demo.
https://codesandbox.io/p/sandbox/95hcm5

The first SelectiveBloomEffect targets the left cube, while the second targets the right cube.  
The second bloom is not even used in the EffectPass, so it shouldn't have any effect. But its `selection` seems to be added to the first.

### Expected behavior

The 2 SelectiveBloomEffect should independently affect their own `selection`. 

### Library versions used

 - Three: 0.167.0
 - Post Processing: 6.36.0

**Comment by vanruesc** [comment]
Selective bloom uses `Selection` which means https://github.com/pmndrs/postprocessing/issues/464#issuecomment-1475017106 applies here as well.

This is fixed in v7, but it probably won't hurt to backport that to v6...

**Comment by thibka** [comment]
Oh that makes sense, thanks!
However, the default `selection.layer` is actually `11`.
