### ISSUE TITLE
Invalid OptimizedCineonToneMapping

### ISSUE THREAD

**Issue by nine-fox** [pmndrs/postprocessing#655]
Hi,

I just found the following code is invalid in ToneMappingEffect.js:

_this.defines.set("toneMapping(texel)", "OptimizedCineonToneMapping(texel)");_

It will emit shader compile error under there.js r168

Change it to the following will remove the error:

_this.defines.set("toneMapping(texel)", "CineonToneMapping(texel)");_

I am using postprocessing 6.36.1

**Comment by vanruesc** [comment]
Oh, thanks for the report. That's a breaking change from `three` that went through unnoticed. I'll work on a fix.

**Comment by vanruesc** [comment]
Fixed in `postprocessing@6.36.2`.
