### ISSUE TITLE
Error prompts regarding the use of EffectComposer

### ISSUE THREAD

**Issue by yywf77** [pmndrs/postprocessing#664]
As shown below, an error message will be displayed during runtime. And I hope to receive your help, thank you!
[.WebGL-0x110053dc700] GL_INVALID_VALUE: Texture dimensions must all be greater than zero.
[.WebGL-0x110053dc700] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete: Attachment has zero size.

import { afterNextRender, ChangeDetectionStrategy, Component, computed, CUSTOM_ELEMENTS_SCHEMA, effect, inject, Injector, signal } from "@angular/core";
import { BlendFunction, EdgeDetectionMode, EffectComposer, EffectPass, KernelSize, OutlineEffect, PredicationMode, RenderPass, SMAAEffect, SMAAPreset } from "postprocessing";
import { injectBeforeRender, injectStore, NgtArgs } from "angular-three";
import { EditorService } from "../editor";
import { NoToneMapping, Object3D } from "three";

@Component({
    selector: 'sm-outline-helper',
    standalone:true,
    template: `<ngt-primitive *args="[effect()]" />`,
    imports: [NgtArgs],
    schemas: [CUSTOM_ELEMENTS_SCHEMA],
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class OutlineHelper{
    readonly store = injectStore();
    private injector = inject(Injector);
    private renderer = this.store.select('gl');
    private scene = this.store.select('scene');
    private camera = this.store.select('camera');
    private size = this.store.select('size');
    private invalidate = this.store.select('invalidate');

    selection = signal<Array<Object3D>>([]);
    selectionLayer = signal<number>(32);

    effect = computed(()=>{
        const [scene,camera,{width,height}] = [this.scene(),this.camera(),this.size()];
        return new OutlineEffect(scene,camera,{
            blendFunction: BlendFunction.SCREEN,
            edgeStrength: 10,
            pulseSpeed: 0.5,
            visibleEdgeColor: 0x00ff00,
            hiddenEdgeColor: 0x00ff00,
            kernelSize:KernelSize.LARGE,
            width:width,
            height:height,
            blur: true,
            xRay: true,
        });
    });

    composer = computed(()=>{
        const [renderer,scene,camera,{width,height}] = [this.renderer(),this.scene(),this.camera(),this.effect(),this.size()];
        const composer = new EffectComposer(renderer);
        composer.setSize(width,height);
        composer.addPass(new RenderPass(scene,camera));

        const smaa = new SMAAEffect({preset:SMAAPreset.HIGH,edgeDetectionMode:EdgeDetectionMode.COLOR,predicationMode:PredicationMode.DEPTH});
        composer.addPass(new EffectPass(camera,smaa));
        return composer;
    });

    enable = signal<boolean>(true);

    constructor(private editorService:EditorService){
        this.editorService.onSelect().subscribe(({object})=>{
            this.selection.update(()=>{
                return [object];
            });
        });

        effect((onCleanup) => {
			const renderer = this.renderer();
			const currentTonemapping = renderer.toneMapping;
			renderer.toneMapping = NoToneMapping;
			onCleanup(() => {
				renderer.toneMapping = currentTonemapping;
			});
		});

        effect((onCleanup) => {
            const [composer,camera,effect] = [this.composer(),this.camera(),this.effect()];
            composer.addPass(new EffectPass(camera,effect))
            onCleanup(() => {
				composer.removeAllPasses();
			});
        });

        effect(()=>{
            const [effect,invalidate,selectionLayer] = [this.effect(),this.invalidate(),this.selectionLayer()];
            effect.selectionLayer = selectionLayer;
            invalidate();
        });

        effect((onCleanup)=>{
            if(this.selection()===undefined){
                throw new Error('need a selection');
            }
            const cleanup = this.handle(this.selection,this.effect,this.invalidate);

            onCleanup(()=>{
                cleanup?.();
            });
        });

        afterNextRender(()=>{
            injectBeforeRender(({delta})=>{
                const [enable,composer] = [this.enable(),this.composer()];
                if(enable){
                    composer.render(delta);
                }
            },{ injector: this.injector, priority: 0 });
        });
    }

	private handle(_selection: () => Array<Object3D> | undefined,_outline: () => OutlineEffect,_invalidate: () => () => void){
        const selection = _selection();
        if(!selection || selection.length===0)return;

        const [outline,invalidate] = [_outline(),_invalidate()];

        outline.selection.set(selection);

        invalidate();

        return ()=>{
            outline.selection.clear();
            invalidate();
        }
    }

}

**Comment by vanruesc** [comment]
The first few lines clearly state that the resolution has not been set correctly.

```
Texture dimensions must all be greater than zero
```

The following syntax looks questionable:

```
const [renderer,scene,camera,{width,height}] = [this.renderer(),this.scene(),this.camera(),this.effect(),this.size()];
```

```
cleanup?.();
```

Please use the [discussions board](https://github.com/pmndrs/postprocessing/discussions) or other channels for general help.

**Comment by yywf77** [comment]
thanks,vanruesc!
